// Mocks generated by Mockito 5.4.6 from annotations
// in belluga_now/test/presentation/tenant/home/screens/tenant_home_provisional_screen/tenant_home_provisional_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:ui' as _i26;

import 'package:auto_route/auto_route.dart' as _i5;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i6;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i7;
import 'package:belluga_now/domain/app_data/app_data.dart' as _i8;
import 'package:belluga_now/domain/app_data/platform_type.dart' as _i28;
import 'package:belluga_now/domain/app_data/value_object/domain_value.dart'
    as _i13;
import 'package:belluga_now/domain/app_data/value_object/environment_name_value.dart'
    as _i10;
import 'package:belluga_now/domain/app_data/value_object/environment_type_value.dart'
    as _i11;
import 'package:belluga_now/domain/app_data/value_object/platform_type_value.dart'
    as _i9;
import 'package:belluga_now/domain/favorite/projections/favorite_resume.dart'
    as _i4;
import 'package:belluga_now/domain/invites/invite_model.dart' as _i19;
import 'package:belluga_now/domain/schedule/event_model.dart' as _i22;
import 'package:belluga_now/domain/tenant/value_objects/icon_url_value.dart'
    as _i14;
import 'package:belluga_now/domain/tenant/value_objects/main_color_value.dart'
    as _i15;
import 'package:belluga_now/domain/tenant/value_objects/main_logo_url_value.dart'
    as _i16;
import 'package:belluga_now/domain/theme_data_settings/theme_data_settings.dart'
    as _i12;
import 'package:belluga_now/domain/venue_event/projections/venue_event_resume.dart'
    as _i18;
import 'package:belluga_now/infrastructure/repositories/app_data_repository.dart'
    as _i27;
import 'package:belluga_now/presentation/tenant/home/screens/tenant_home_provisional_screen/controllers/tenant_home_provisional_controller.dart'
    as _i17;
import 'package:belluga_now/presentation/tenant/home/screens/tenant_home_provisional_screen/widgets/agenda_section/controllers/tenant_home_agenda_controller.dart'
    as _i21;
import 'package:belluga_now/presentation/tenant/home/screens/tenant_home_screen/widgets/favorite_section/controllers/favorites_section_controller.dart'
    as _i24;
import 'package:belluga_now/presentation/tenant/schedule/screens/event_search_screen/models/invite_filter.dart'
    as _i23;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:stream_value/core/stream_value.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamValue_0<T> extends _i1.SmartFake
    implements _i2.StreamValue<T> {
  _FakeStreamValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusNode_2 extends _i1.SmartFake implements _i3.FocusNode {
  _FakeFocusNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeFavoriteResume_3 extends _i1.SmartFake
    implements _i4.FavoriteResume {
  _FakeFavoriteResume_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKey_4 extends _i1.SmartFake implements _i3.Key {
  _FakeKey_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePendingRoutesHandler_5 extends _i1.SmartFake
    implements _i5.PendingRoutesHandler {
  _FakePendingRoutesHandler_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagelessRoutesObserver_6 extends _i1.SmartFake
    implements _i5.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActiveGuardObserver_7 extends _i1.SmartFake
    implements _i5.ActiveGuardObserver {
  _FakeActiveGuardObserver_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_8<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteCollection_9 extends _i1.SmartFake
    implements _i5.RouteCollection {
  _FakeRouteCollection_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatcher_10 extends _i1.SmartFake implements _i6.RouteMatcher {
  _FakeRouteMatcher_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_11<R> extends _i1.SmartFake implements _i5.RouteData<R> {
  _FakeRouteData_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalObjectKey_12<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalObjectKey<T> {
  _FakeGlobalObjectKey_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNavigationHistory_13 extends _i1.SmartFake
    implements _i7.NavigationHistory {
  _FakeNavigationHistory_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUrlState_14 extends _i1.SmartFake implements _i5.UrlState {
  _FakeUrlState_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRootStackRouter_15 extends _i1.SmartFake
    implements _i5.RootStackRouter {
  _FakeRootStackRouter_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatch_16<T> extends _i1.SmartFake implements _i5.RouteMatch<T> {
  _FakeRouteMatch_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_17 extends _i1.SmartFake
    implements _i5.RoutingController {
  _FakeRoutingController_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppData_18 extends _i1.SmartFake implements _i8.AppData {
  _FakeAppData_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformTypeValue_19 extends _i1.SmartFake
    implements _i9.PlatformTypeValue {
  _FakePlatformTypeValue_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnvironmentNameValue_20 extends _i1.SmartFake
    implements _i10.EnvironmentNameValue {
  _FakeEnvironmentNameValue_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnvironmentTypeValue_21 extends _i1.SmartFake
    implements _i11.EnvironmentTypeValue {
  _FakeEnvironmentTypeValue_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeDataSettings_22 extends _i1.SmartFake
    implements _i12.ThemeDataSettings {
  _FakeThemeDataSettings_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDomainValue_23 extends _i1.SmartFake implements _i13.DomainValue {
  _FakeDomainValue_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIconUrlValue_24 extends _i1.SmartFake implements _i14.IconUrlValue {
  _FakeIconUrlValue_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMainColorValue_25 extends _i1.SmartFake
    implements _i15.MainColorValue {
  _FakeMainColorValue_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMainLogoUrlValue_26 extends _i1.SmartFake
    implements _i16.MainLogoUrlValue {
  _FakeMainLogoUrlValue_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TenantHomeProvisionalController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantHomeProvisionalController extends _i1.Mock
    implements _i17.TenantHomeProvisionalController {
  @override
  _i2.StreamValue<List<_i18.VenueEventResume>>
      get myEventsFilteredStreamValue => (super.noSuchMethod(
            Invocation.getter(#myEventsFilteredStreamValue),
            returnValue: _FakeStreamValue_0<List<_i18.VenueEventResume>>(
              this,
              Invocation.getter(#myEventsFilteredStreamValue),
            ),
            returnValueForMissingStub:
                _FakeStreamValue_0<List<_i18.VenueEventResume>>(
              this,
              Invocation.getter(#myEventsFilteredStreamValue),
            ),
          ) as _i2.StreamValue<List<_i18.VenueEventResume>>);

  @override
  _i2.StreamValue<String?> get userAddressStreamValue => (super.noSuchMethod(
        Invocation.getter(#userAddressStreamValue),
        returnValue: _FakeStreamValue_0<String?>(
          this,
          Invocation.getter(#userAddressStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<String?>(
          this,
          Invocation.getter(#userAddressStreamValue),
        ),
      ) as _i2.StreamValue<String?>);

  @override
  _i2.StreamValue<Set<String>> get confirmedIdsStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#confirmedIdsStreamValue),
        returnValue: _FakeStreamValue_0<Set<String>>(
          this,
          Invocation.getter(#confirmedIdsStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<Set<String>>(
          this,
          Invocation.getter(#confirmedIdsStreamValue),
        ),
      ) as _i2.StreamValue<Set<String>>);

  @override
  _i2.StreamValue<List<_i19.InviteModel>> get pendingInvitesStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#pendingInvitesStreamValue),
        returnValue: _FakeStreamValue_0<List<_i19.InviteModel>>(
          this,
          Invocation.getter(#pendingInvitesStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<List<_i19.InviteModel>>(
          this,
          Invocation.getter(#pendingInvitesStreamValue),
        ),
      ) as _i2.StreamValue<List<_i19.InviteModel>>);

  @override
  _i20.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  String? distanceLabelForMyEvent(_i18.VenueEventResume? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #distanceLabelForMyEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  void onDispose() => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TenantHomeAgendaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantHomeAgendaController extends _i1.Mock
    implements _i21.TenantHomeAgendaController {
  @override
  _i3.TextEditingController get searchController => (super.noSuchMethod(
        Invocation.getter(#searchController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#searchController),
        ),
        returnValueForMissingStub: _FakeTextEditingController_1(
          this,
          Invocation.getter(#searchController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i3.FocusNode get focusNode => (super.noSuchMethod(
        Invocation.getter(#focusNode),
        returnValue: _FakeFocusNode_2(
          this,
          Invocation.getter(#focusNode),
        ),
        returnValueForMissingStub: _FakeFocusNode_2(
          this,
          Invocation.getter(#focusNode),
        ),
      ) as _i3.FocusNode);

  @override
  _i2.StreamValue<List<_i22.EventModel>> get displayedEventsStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#displayedEventsStreamValue),
        returnValue: _FakeStreamValue_0<List<_i22.EventModel>>(
          this,
          Invocation.getter(#displayedEventsStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<List<_i22.EventModel>>(
          this,
          Invocation.getter(#displayedEventsStreamValue),
        ),
      ) as _i2.StreamValue<List<_i22.EventModel>>);

  @override
  _i2.StreamValue<bool> get isInitialLoadingStreamValue => (super.noSuchMethod(
        Invocation.getter(#isInitialLoadingStreamValue),
        returnValue: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#isInitialLoadingStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#isInitialLoadingStreamValue),
        ),
      ) as _i2.StreamValue<bool>);

  @override
  _i2.StreamValue<bool> get isPageLoadingStreamValue => (super.noSuchMethod(
        Invocation.getter(#isPageLoadingStreamValue),
        returnValue: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#isPageLoadingStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#isPageLoadingStreamValue),
        ),
      ) as _i2.StreamValue<bool>);

  @override
  _i2.StreamValue<bool> get hasMoreStreamValue => (super.noSuchMethod(
        Invocation.getter(#hasMoreStreamValue),
        returnValue: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#hasMoreStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#hasMoreStreamValue),
        ),
      ) as _i2.StreamValue<bool>);

  @override
  _i2.StreamValue<bool> get showHistoryStreamValue => (super.noSuchMethod(
        Invocation.getter(#showHistoryStreamValue),
        returnValue: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#showHistoryStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#showHistoryStreamValue),
        ),
      ) as _i2.StreamValue<bool>);

  @override
  _i2.StreamValue<bool> get searchActiveStreamValue => (super.noSuchMethod(
        Invocation.getter(#searchActiveStreamValue),
        returnValue: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#searchActiveStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<bool>(
          this,
          Invocation.getter(#searchActiveStreamValue),
        ),
      ) as _i2.StreamValue<bool>);

  @override
  _i2.StreamValue<_i23.InviteFilter> get inviteFilterStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#inviteFilterStreamValue),
        returnValue: _FakeStreamValue_0<_i23.InviteFilter>(
          this,
          Invocation.getter(#inviteFilterStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<_i23.InviteFilter>(
          this,
          Invocation.getter(#inviteFilterStreamValue),
        ),
      ) as _i2.StreamValue<_i23.InviteFilter>);

  @override
  _i2.StreamValue<double> get radiusMetersStreamValue => (super.noSuchMethod(
        Invocation.getter(#radiusMetersStreamValue),
        returnValue: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#radiusMetersStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#radiusMetersStreamValue),
        ),
      ) as _i2.StreamValue<double>);

  @override
  _i2.StreamValue<double> get maxRadiusMetersStreamValue => (super.noSuchMethod(
        Invocation.getter(#maxRadiusMetersStreamValue),
        returnValue: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#maxRadiusMetersStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#maxRadiusMetersStreamValue),
        ),
      ) as _i2.StreamValue<double>);

  @override
  _i20.Future<void> init({bool? startWithHistory = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#startWithHistory: startWithHistory},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> loadNextPage() => (super.noSuchMethod(
        Invocation.method(
          #loadNextPage,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void toggleHistory() => super.noSuchMethod(
        Invocation.method(
          #toggleHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInviteFilter(_i23.InviteFilter? filter) => super.noSuchMethod(
        Invocation.method(
          #setInviteFilter,
          [filter],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cycleInviteFilter() => super.noSuchMethod(
        Invocation.method(
          #cycleInviteFilter,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSearchActive(bool? active) => super.noSuchMethod(
        Invocation.method(
          #setSearchActive,
          [active],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSearchMode() => super.noSuchMethod(
        Invocation.method(
          #toggleSearchMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRadiusMeters(double? meters) => super.noSuchMethod(
        Invocation.method(
          #setRadiusMeters,
          [meters],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInitialSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setInitialSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> searchEvents(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [query],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  bool isEventConfirmed(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #isEventConfirmed,
          [eventId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int pendingInviteCount(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #pendingInviteCount,
          [eventId],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String? distanceLabelFor(_i18.VenueEventResume? event) => (super.noSuchMethod(
        Invocation.method(
          #distanceLabelFor,
          [event],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  void onDispose() => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FavoritesSectionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesSectionController extends _i1.Mock
    implements _i24.FavoritesSectionController {
  @override
  _i2.StreamValue<List<_i4.FavoriteResume>?> get favoritesStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#favoritesStreamValue),
        returnValue: _FakeStreamValue_0<List<_i4.FavoriteResume>?>(
          this,
          Invocation.getter(#favoritesStreamValue),
        ),
        returnValueForMissingStub:
            _FakeStreamValue_0<List<_i4.FavoriteResume>?>(
          this,
          Invocation.getter(#favoritesStreamValue),
        ),
      ) as _i2.StreamValue<List<_i4.FavoriteResume>?>);

  @override
  _i20.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i4.FavoriteResume buildPinnedFavorite() => (super.noSuchMethod(
        Invocation.method(
          #buildPinnedFavorite,
          [],
        ),
        returnValue: _FakeFavoriteResume_3(
          this,
          Invocation.method(
            #buildPinnedFavorite,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFavoriteResume_3(
          this,
          Invocation.method(
            #buildPinnedFavorite,
            [],
          ),
        ),
      ) as _i4.FavoriteResume);

  @override
  void onDispose() => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StackRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouter extends _i1.Mock implements _i5.StackRouter {
  @override
  _i3.Key get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _FakeKey_4(
          this,
          Invocation.getter(#key),
        ),
        returnValueForMissingStub: _FakeKey_4(
          this,
          Invocation.getter(#key),
        ),
      ) as _i3.Key);

  @override
  _i3.Key get matchId => (super.noSuchMethod(
        Invocation.getter(#matchId),
        returnValue: _FakeKey_4(
          this,
          Invocation.getter(#matchId),
        ),
        returnValueForMissingStub: _FakeKey_4(
          this,
          Invocation.getter(#matchId),
        ),
      ) as _i3.Key);

  @override
  _i5.PendingRoutesHandler get pendingRoutesHandler => (super.noSuchMethod(
        Invocation.getter(#pendingRoutesHandler),
        returnValue: _FakePendingRoutesHandler_5(
          this,
          Invocation.getter(#pendingRoutesHandler),
        ),
        returnValueForMissingStub: _FakePendingRoutesHandler_5(
          this,
          Invocation.getter(#pendingRoutesHandler),
        ),
      ) as _i5.PendingRoutesHandler);

  @override
  int get stateHash => (super.noSuchMethod(
        Invocation.getter(#stateHash),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.PagelessRoutesObserver get pagelessRoutesObserver => (super.noSuchMethod(
        Invocation.getter(#pagelessRoutesObserver),
        returnValue: _FakePagelessRoutesObserver_6(
          this,
          Invocation.getter(#pagelessRoutesObserver),
        ),
        returnValueForMissingStub: _FakePagelessRoutesObserver_6(
          this,
          Invocation.getter(#pagelessRoutesObserver),
        ),
      ) as _i5.PagelessRoutesObserver);

  @override
  _i5.ActiveGuardObserver get activeGuardObserver => (super.noSuchMethod(
        Invocation.getter(#activeGuardObserver),
        returnValue: _FakeActiveGuardObserver_7(
          this,
          Invocation.getter(#activeGuardObserver),
        ),
        returnValueForMissingStub: _FakeActiveGuardObserver_7(
          this,
          Invocation.getter(#activeGuardObserver),
        ),
      ) as _i5.ActiveGuardObserver);

  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_8<_i3.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
        returnValueForMissingStub: _FakeGlobalKey_8<_i3.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i3.GlobalKey<_i3.NavigatorState>);

  @override
  _i5.RouteCollection get routeCollection => (super.noSuchMethod(
        Invocation.getter(#routeCollection),
        returnValue: _FakeRouteCollection_9(
          this,
          Invocation.getter(#routeCollection),
        ),
        returnValueForMissingStub: _FakeRouteCollection_9(
          this,
          Invocation.getter(#routeCollection),
        ),
      ) as _i5.RouteCollection);

  @override
  _i6.RouteMatcher get matcher => (super.noSuchMethod(
        Invocation.getter(#matcher),
        returnValue: _FakeRouteMatcher_10(
          this,
          Invocation.getter(#matcher),
        ),
        returnValueForMissingStub: _FakeRouteMatcher_10(
          this,
          Invocation.getter(#matcher),
        ),
      ) as _i6.RouteMatcher);

  @override
  _i5.RouteData<dynamic> get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#current),
        ),
        returnValueForMissingStub: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#current),
        ),
      ) as _i5.RouteData<dynamic>);

  @override
  _i5.RouteData<dynamic> get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#topRoute),
        ),
        returnValueForMissingStub: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i5.RouteData<dynamic>);

  @override
  bool get hasPagelessTopRoute => (super.noSuchMethod(
        Invocation.getter(#hasPagelessTopRoute),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i5.AutoRoutePage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i5.AutoRoutePage<dynamic>>[],
        returnValueForMissingStub: <_i5.AutoRoutePage<dynamic>>[],
      ) as List<_i5.AutoRoutePage<dynamic>>);

  @override
  bool get ignorePopCompleters => (super.noSuchMethod(
        Invocation.getter(#ignorePopCompleters),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.GlobalObjectKey<_i3.State<_i3.StatefulWidget>> get globalRouterKey =>
      (super.noSuchMethod(
        Invocation.getter(#globalRouterKey),
        returnValue: _FakeGlobalObjectKey_12<_i3.State<_i3.StatefulWidget>>(
          this,
          Invocation.getter(#globalRouterKey),
        ),
        returnValueForMissingStub:
            _FakeGlobalObjectKey_12<_i3.State<_i3.StatefulWidget>>(
          this,
          Invocation.getter(#globalRouterKey),
        ),
      ) as _i3.GlobalObjectKey<_i3.State<_i3.StatefulWidget>>);

  @override
  List<_i5.RoutingController> get childControllers => (super.noSuchMethod(
        Invocation.getter(#childControllers),
        returnValue: <_i5.RoutingController>[],
        returnValueForMissingStub: <_i5.RoutingController>[],
      ) as List<_i5.RoutingController>);

  @override
  _i7.NavigationHistory get navigationHistory => (super.noSuchMethod(
        Invocation.getter(#navigationHistory),
        returnValue: _FakeNavigationHistory_13(
          this,
          Invocation.getter(#navigationHistory),
        ),
        returnValueForMissingStub: _FakeNavigationHistory_13(
          this,
          Invocation.getter(#navigationHistory),
        ),
      ) as _i7.NavigationHistory);

  @override
  _i5.UrlState get urlState => (super.noSuchMethod(
        Invocation.getter(#urlState),
        returnValue: _FakeUrlState_14(
          this,
          Invocation.getter(#urlState),
        ),
        returnValueForMissingStub: _FakeUrlState_14(
          this,
          Invocation.getter(#urlState),
        ),
      ) as _i5.UrlState);

  @override
  String get currentPath => (super.noSuchMethod(
        Invocation.getter(#currentPath),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#currentPath),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#currentPath),
        ),
      ) as String);

  @override
  String get currentUrl => (super.noSuchMethod(
        Invocation.getter(#currentUrl),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#currentUrl),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#currentUrl),
        ),
      ) as String);

  @override
  List<_i5.RouteData<dynamic>> get stackData => (super.noSuchMethod(
        Invocation.getter(#stackData),
        returnValue: <_i5.RouteData<dynamic>>[],
        returnValueForMissingStub: <_i5.RouteData<dynamic>>[],
      ) as List<_i5.RouteData<dynamic>>);

  @override
  bool get managedByWidget => (super.noSuchMethod(
        Invocation.getter(#managedByWidget),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isTopMost => (super.noSuchMethod(
        Invocation.getter(#isTopMost),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canNavigateBack => (super.noSuchMethod(
        Invocation.getter(#canNavigateBack),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.RootStackRouter get root => (super.noSuchMethod(
        Invocation.getter(#root),
        returnValue: _FakeRootStackRouter_15(
          this,
          Invocation.getter(#root),
        ),
        returnValueForMissingStub: _FakeRootStackRouter_15(
          this,
          Invocation.getter(#root),
        ),
      ) as _i5.RootStackRouter);

  @override
  bool get isRoot => (super.noSuchMethod(
        Invocation.getter(#isRoot),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.RouteMatch<dynamic> get topMatch => (super.noSuchMethod(
        Invocation.getter(#topMatch),
        returnValue: _FakeRouteMatch_16<dynamic>(
          this,
          Invocation.getter(#topMatch),
        ),
        returnValueForMissingStub: _FakeRouteMatch_16<dynamic>(
          this,
          Invocation.getter(#topMatch),
        ),
      ) as _i5.RouteMatch<dynamic>);

  @override
  _i5.RouteData<dynamic> get routeData => (super.noSuchMethod(
        Invocation.getter(#routeData),
        returnValue: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#routeData),
        ),
        returnValueForMissingStub: _FakeRouteData_11<dynamic>(
          this,
          Invocation.getter(#routeData),
        ),
      ) as _i5.RouteData<dynamic>);

  @override
  bool get hasEntries => (super.noSuchMethod(
        Invocation.getter(#hasEntries),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get pageCount => (super.noSuchMethod(
        Invocation.getter(#pageCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i5.RouteMatch<dynamic>> get currentSegments => (super.noSuchMethod(
        Invocation.getter(#currentSegments),
        returnValue: <_i5.RouteMatch<dynamic>>[],
        returnValueForMissingStub: <_i5.RouteMatch<dynamic>>[],
      ) as List<_i5.RouteMatch<dynamic>>);

  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #ignorePopCompleters,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> reevaluateGuards() => (super.noSuchMethod(
        Invocation.method(
          #reevaluateGuards,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canPop,
          [],
          {
            #ignoreChildRoutes: ignoreChildRoutes,
            #ignoreParentRoutes: ignoreParentRoutes,
            #ignorePagelessRoutes: ignorePagelessRoutes,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i20.Future<T?> pushWidget<T extends Object?>(
    _i3.Widget? widget, {
    _i3.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushWidget,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
            #opaque: opaque,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<T?> pushNativeRoute<T extends Object?>(_i3.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
        Invocation.method(
          #maybePop,
          [result],
        ),
        returnValue: _i20.Future<bool>.value(false),
        returnValueForMissingStub: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void removeRoute(
    _i5.RouteData<dynamic>? route, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRoute,
          [route],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPopPage(_i5.AutoRoutePage<Object?>? page) => super.noSuchMethod(
        Invocation.method(
          #onPopPage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<T?> push<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<void> insert(
    _i5.PageRouteInfo<Object?>? route, {
    int? index = 0,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [route],
          {
            #index: index,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<T?> replace<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<void> pushAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> popAndPushAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> replaceAll(
    List<_i5.PageRouteInfo<Object?>>? routes, {
    _i5.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [routes],
          {
            #onFailure: onFailure,
            #updateExistingRoutes: updateExistingRoutes,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void popUntilRoot() => super.noSuchMethod(
        Invocation.method(
          #popUntilRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    TO? result,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPush,
          [route],
          {
            #result: result,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  bool removeUntil(
    _i5.RouteDataPredicate? predicate, {
    bool? scoped = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i3.RoutePredicate? predicate, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool removeWhere(
    _i5.RouteDataPredicate? predicate, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [predicate],
          {#notify: notify},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void updateDeclarativeRoutes(List<_i5.PageRouteInfo<Object?>>? routes) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDeclarativeRoutes,
          [routes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> navigateAll(
    List<_i5.RouteMatch<dynamic>>? routes, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<T?> pushAndPopUntil<T extends Object?>(
    _i5.PageRouteInfo<Object?>? route, {
    required _i3.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAndPopUntil,
          [route],
          {
            #predicate: predicate,
            #scopedPopUntil: scopedPopUntil,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<T?> replacePath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replacePath,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<T?> pushPath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushPath,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  _i20.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<T?>.value(),
        returnValueForMissingStub: _i20.Future<T?>.value(),
      ) as _i20.Future<T?>);

  @override
  void popUntilRouteWithName(
    String? name, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithName,
          [name],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popUntilRouteWithPath(
    String? path, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithPath,
          [path],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markUrlStateForReplace() => super.noSuchMethod(
        Invocation.method(
          #markUrlStateForReplace,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void attachChildController(_i5.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #attachChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeChildController(_i5.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #removeChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
        Invocation.method(
          #notifyAll,
          [],
          {#forceUrlRebuild: forceUrlRebuild},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentHierarchy,
          [],
          {
            #asPath: asPath,
            #ignorePending: ignorePending,
            #ignoreParams: ignoreParams,
          },
        ),
        returnValue: <_i5.HierarchySegment>[],
        returnValueForMissingStub: <_i5.HierarchySegment>[],
      ) as List<_i5.HierarchySegment>);

  @override
  bool isRouteActive(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #isRouteActive,
          [routeName],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isRouteDataActive(_i5.RouteData<dynamic>? data) => (super.noSuchMethod(
        Invocation.method(
          #isRouteDataActive,
          [data],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isPathActive(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isPathActive,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.RouteMatch<dynamic>? match(_i5.PageRouteInfo<Object?>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #match,
          [route],
        ),
        returnValueForMissingStub: null,
      ) as _i5.RouteMatch<dynamic>?);

  @override
  _i20.Future<dynamic> navigate(
    _i5.PageRouteInfo<Object?>? route, {
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigate,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i20.Future<dynamic>.value(),
        returnValueForMissingStub: _i20.Future<dynamic>.value(),
      ) as _i20.Future<dynamic>);

  @override
  _i20.Future<void> navigatePath(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigatePath,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i5.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void back() => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushPathState(Object? state) => super.noSuchMethod(
        Invocation.method(
          #pushPathState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_17(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
        returnValueForMissingStub: _FakeRoutingController_17(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i5.RoutingController);

  @override
  void updateRouteData(_i5.RouteData<dynamic>? data) => super.noSuchMethod(
        Invocation.method(
          #updateRouteData,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T? innerRouterOf<T extends _i5.RoutingController>(String? routeName) =>
      (super.noSuchMethod(
        Invocation.method(
          #innerRouterOf,
          [routeName],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i20.Future<bool> maybePopTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
        Invocation.method(
          #maybePopTop,
          [result],
        ),
        returnValue: _i20.Future<bool>.value(false),
        returnValueForMissingStub: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void popTop<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popTop,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool childrenCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #childrenCanPop,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool activeRouterCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #activeRouterCanPop,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.PageRouteInfo<Object?>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPageRoute,
          [path],
          {#includePrefixMatches: includePrefixMatches},
        ),
        returnValueForMissingStub: null,
      ) as _i5.PageRouteInfo<Object?>?);

  @override
  List<_i5.PageRouteInfo<Object?>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildPageRoutesStack,
          [path],
          {#includePrefixMatches: includePrefixMatches},
        ),
        returnValueForMissingStub: null,
      ) as List<_i5.PageRouteInfo<Object?>>?);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDataRepository extends _i1.Mock implements _i27.AppDataRepository {
  @override
  _i8.AppData get appData => (super.noSuchMethod(
        Invocation.getter(#appData),
        returnValue: _FakeAppData_18(
          this,
          Invocation.getter(#appData),
        ),
        returnValueForMissingStub: _FakeAppData_18(
          this,
          Invocation.getter(#appData),
        ),
      ) as _i8.AppData);

  @override
  _i2.StreamValue<_i3.ThemeMode?> get themeModeStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#themeModeStreamValue),
        returnValue: _FakeStreamValue_0<_i3.ThemeMode?>(
          this,
          Invocation.getter(#themeModeStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<_i3.ThemeMode?>(
          this,
          Invocation.getter(#themeModeStreamValue),
        ),
      ) as _i2.StreamValue<_i3.ThemeMode?>);

  @override
  _i2.StreamValue<double> get maxRadiusMetersStreamValue => (super.noSuchMethod(
        Invocation.getter(#maxRadiusMetersStreamValue),
        returnValue: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#maxRadiusMetersStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<double>(
          this,
          Invocation.getter(#maxRadiusMetersStreamValue),
        ),
      ) as _i2.StreamValue<double>);

  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
        returnValueForMissingStub: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  double get maxRadiusMeters => (super.noSuchMethod(
        Invocation.getter(#maxRadiusMeters),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  set appData(_i8.AppData? value) => super.noSuchMethod(
        Invocation.setter(
          #appData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setThemeMode(_i3.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setMaxRadiusMeters(double? meters) => (super.noSuchMethod(
        Invocation.method(
          #setMaxRadiusMeters,
          [meters],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [AppData].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppData extends _i1.Mock implements _i8.AppData {
  @override
  _i9.PlatformTypeValue get platformType => (super.noSuchMethod(
        Invocation.getter(#platformType),
        returnValue: _FakePlatformTypeValue_19(
          this,
          Invocation.getter(#platformType),
        ),
        returnValueForMissingStub: _FakePlatformTypeValue_19(
          this,
          Invocation.getter(#platformType),
        ),
      ) as _i9.PlatformTypeValue);

  @override
  String get hostname => (super.noSuchMethod(
        Invocation.getter(#hostname),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#hostname),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#hostname),
        ),
      ) as String);

  @override
  String get href => (super.noSuchMethod(
        Invocation.getter(#href),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#href),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#href),
        ),
      ) as String);

  @override
  String get device => (super.noSuchMethod(
        Invocation.getter(#device),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#device),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#device),
        ),
      ) as String);

  @override
  _i10.EnvironmentNameValue get nameValue => (super.noSuchMethod(
        Invocation.getter(#nameValue),
        returnValue: _FakeEnvironmentNameValue_20(
          this,
          Invocation.getter(#nameValue),
        ),
        returnValueForMissingStub: _FakeEnvironmentNameValue_20(
          this,
          Invocation.getter(#nameValue),
        ),
      ) as _i10.EnvironmentNameValue);

  @override
  _i11.EnvironmentTypeValue get typeValue => (super.noSuchMethod(
        Invocation.getter(#typeValue),
        returnValue: _FakeEnvironmentTypeValue_21(
          this,
          Invocation.getter(#typeValue),
        ),
        returnValueForMissingStub: _FakeEnvironmentTypeValue_21(
          this,
          Invocation.getter(#typeValue),
        ),
      ) as _i11.EnvironmentTypeValue);

  @override
  _i12.ThemeDataSettings get themeDataSettings => (super.noSuchMethod(
        Invocation.getter(#themeDataSettings),
        returnValue: _FakeThemeDataSettings_22(
          this,
          Invocation.getter(#themeDataSettings),
        ),
        returnValueForMissingStub: _FakeThemeDataSettings_22(
          this,
          Invocation.getter(#themeDataSettings),
        ),
      ) as _i12.ThemeDataSettings);

  @override
  _i13.DomainValue get mainDomainValue => (super.noSuchMethod(
        Invocation.getter(#mainDomainValue),
        returnValue: _FakeDomainValue_23(
          this,
          Invocation.getter(#mainDomainValue),
        ),
        returnValueForMissingStub: _FakeDomainValue_23(
          this,
          Invocation.getter(#mainDomainValue),
        ),
      ) as _i13.DomainValue);

  @override
  List<_i13.DomainValue> get domains => (super.noSuchMethod(
        Invocation.getter(#domains),
        returnValue: <_i13.DomainValue>[],
        returnValueForMissingStub: <_i13.DomainValue>[],
      ) as List<_i13.DomainValue>);

  @override
  _i14.IconUrlValue get mainIconLightUrl => (super.noSuchMethod(
        Invocation.getter(#mainIconLightUrl),
        returnValue: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#mainIconLightUrl),
        ),
        returnValueForMissingStub: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#mainIconLightUrl),
        ),
      ) as _i14.IconUrlValue);

  @override
  _i14.IconUrlValue get mainIconDarkUrl => (super.noSuchMethod(
        Invocation.getter(#mainIconDarkUrl),
        returnValue: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#mainIconDarkUrl),
        ),
        returnValueForMissingStub: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#mainIconDarkUrl),
        ),
      ) as _i14.IconUrlValue);

  @override
  _i15.MainColorValue get mainColor => (super.noSuchMethod(
        Invocation.getter(#mainColor),
        returnValue: _FakeMainColorValue_25(
          this,
          Invocation.getter(#mainColor),
        ),
        returnValueForMissingStub: _FakeMainColorValue_25(
          this,
          Invocation.getter(#mainColor),
        ),
      ) as _i15.MainColorValue);

  @override
  _i16.MainLogoUrlValue get mainLogoLightUrl => (super.noSuchMethod(
        Invocation.getter(#mainLogoLightUrl),
        returnValue: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoLightUrl),
        ),
        returnValueForMissingStub: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoLightUrl),
        ),
      ) as _i16.MainLogoUrlValue);

  @override
  _i16.MainLogoUrlValue get mainLogoDarkUrl => (super.noSuchMethod(
        Invocation.getter(#mainLogoDarkUrl),
        returnValue: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoDarkUrl),
        ),
        returnValueForMissingStub: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoDarkUrl),
        ),
      ) as _i16.MainLogoUrlValue);

  @override
  _i28.PlatformType get appType => (super.noSuchMethod(
        Invocation.getter(#appType),
        returnValue: _i28.PlatformType.web,
        returnValueForMissingStub: _i28.PlatformType.web,
      ) as _i28.PlatformType);

  @override
  _i14.IconUrlValue get iconUrl => (super.noSuchMethod(
        Invocation.getter(#iconUrl),
        returnValue: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#iconUrl),
        ),
        returnValueForMissingStub: _FakeIconUrlValue_24(
          this,
          Invocation.getter(#iconUrl),
        ),
      ) as _i14.IconUrlValue);

  @override
  _i16.MainLogoUrlValue get mainLogoUrl => (super.noSuchMethod(
        Invocation.getter(#mainLogoUrl),
        returnValue: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoUrl),
        ),
        returnValueForMissingStub: _FakeMainLogoUrlValue_26(
          this,
          Invocation.getter(#mainLogoUrl),
        ),
      ) as _i16.MainLogoUrlValue);

  @override
  String get schema => (super.noSuchMethod(
        Invocation.getter(#schema),
        returnValue: _i25.dummyValue<String>(
          this,
          Invocation.getter(#schema),
        ),
        returnValueForMissingStub: _i25.dummyValue<String>(
          this,
          Invocation.getter(#schema),
        ),
      ) as String);
}
