enum CanonicalRouteFamily {
  tenantHome,
  tenantPrivacyPolicy,
  discoveryRoot,
  partnerDetail,
  profileRoot,
  accountDeletionResolution,
  eventSearch,
  immersiveEventDetail,
  cityMap,
  poiDetail,
  inviteFlow,
  inviteEntry,
  inviteShare,
  appPromotion,
  authLogin,
  recoveryPassword,
  authCreateNewPassword,
  landlordHome,
  accountWorkspaceHome,
  accountWorkspaceScoped,
  accountWorkspaceCreateEvent,
  tenantAdminDashboard,
  tenantAdminEventsRoot,
  tenantAdminEventsInternal,
  tenantAdminAccountsRoot,
  tenantAdminAccountsInternal,
  tenantAdminTaxonomiesRoot,
  tenantAdminTaxonomiesInternal,
  tenantAdminFiltersRoot,
  tenantAdminFiltersInternal,
  tenantAdminSettingsRoot,
  tenantAdminSettingsInternal,
}

enum RouteChromeMode { standard, fullscreen, scopedSectionAppBar }

enum AdminShellSection {
  dashboard,
  events,
  accounts,
  taxonomies,
  filters,
  settings,
}
