const List<Map<String, dynamic>> poisGoogleData = <Map<String, dynamic>>[
  {
    'name': 'Vitória espírito santo',
    'description': '',
    'address':
        'Parque da Areia Preta, Guarapari - State of Espírito Santo, 29200-260',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6740776,
    'longitude': -40.5003145,
    'rating': 4.4,
  },
  {
    'name': 'Ponta da praia dos Namorados',
    'description': '',
    'address':
        'R. Nilza Teresa Hofman Pádua, 90 - Centro, Guarapari - ES, 29200-300',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.6716618,
    'longitude': -40.4949483,
    'rating': 4.8,
  },
  {
    'name': 'Praia da Areia Preta',
    'description': '',
    'address':
        'Praça Ciríaco Ramalhete de Oliveira - Centro, Guarapari - ES, 29200-380',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.6747497,
    'longitude': -40.4989703,
    'rating': 4.7,
  },
  {
    'name': 'Praia das Castanheiras',
    'description': '',
    'address':
        'Av. Des. Lourival de Almeida, 7 - São Judas Tadeu, Guarapari - ES, 29200-250',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'São Judas Tadeu',
    'latitude': -20.6735433,
    'longitude': -40.4973606,
    'rating': null,
  },
  {
    'name': 'Beach of Virtues',
    'description': '',
    'address': 'Av. Edízio Cirne - Centro, Guarapari - ES, 29200-080',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach',
    'borough': 'Centro',
    'latitude': -20.6691588,
    'longitude': -40.4924506,
    'rating': 4.7,
  },
  {
    'name': 'Parque Natural Municipal Morro da Pescaria',
    'description':
        'Walking trails end at the beach at this picturesque park & hiking area with sea views.',
    'address': 'Av. Beira Mar, 30 - Praia do Morro, Guarapari - ES, 29216-010',
    'category': 'attractions',
    'subtypes':
        'Tourist attraction, Ecological park, Hiking area, Public beach, City park',
    'borough': 'Praia do Morro',
    'latitude': -20.6570748,
    'longitude': -40.4718304,
    'rating': 4.7,
  },
  {
    'name': 'Bacutia Guarapari',
    'description': '',
    'address':
        'Parque da Areia Preta, Guarapari - State of Espírito Santo, 29200-260',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6738927,
    'longitude': -40.4999838,
    'rating': 4.8,
  },
  {
    'name': 'Paulo César Vinha State Park',
    'description':
        'Expansive waterfront park offering a visitor center & diverse environments, including a dry forest.',
    'address':
        'Rodovia ES-060, Km 37,5, s/n - Praia de Setiba, Guarapari - ES, 29200-000',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, State park',
    'borough': 'Praia de Setiba',
    'latitude': -20.603062,
    'longitude': -40.426015,
    'rating': 4.7,
  },
  {
    'name': 'Três Praias, Guarapari - ES',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach, Scenic spot',
    'borough': 'Guarapari',
    'latitude': -20.6373953,
    'longitude': -40.4688563,
    'rating': 4.8,
  },
  {
    'name': 'MURAL DOS JOGADORES',
    'description': '',
    'address': 'R. Floriano Peixoto, 3 - Ipiranga, Guarapari - ES, 29201-093',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Ipiranga',
    'latitude': -20.6777548,
    'longitude': -40.5098136,
    'rating': 5.0,
  },
  {
    'name': 'Letreiro de Guarapari',
    'description': '',
    'address': 'Praca Gov. Bley, 159 - Centro, Guarapari - ES, 29200-185',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.674518,
    'longitude': -40.498356,
    'rating': 5.0,
  },
  {
    'name': 'Estátua do Tigrão',
    'description': '',
    'address': 'Av. Pedro Ramos - Centro, Guarapari - ES, 29200-172',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Sculpture',
    'borough': 'Centro',
    'latitude': -20.6687749,
    'longitude': -40.4988488,
    'rating': 4.7,
  },
  {
    'name': 'Praia do Morro, Guarapari-ES',
    'description': '',
    'address': 'Praia do Morro, Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach',
    'borough': 'Praia do Morro',
    'latitude': -20.654661,
    'longitude': -40.4876494,
    'rating': 4.7,
  },
  {
    'name': 'Ancoradouro - Canal de Guarapari',
    'description': '',
    'address': 'Av. Pedro Ramos - Parque da Areia Preta, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6702586,
    'longitude': -40.5028548,
    'rating': 4.7,
  },
  {
    'name': 'Estátua de Golfinho',
    'description': '',
    'address':
        'Parque Natural Municipal Morro da Pescaria - Praia do Morro, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6561795,
    'longitude': -40.4741489,
    'rating': 4.6,
  },
  {
    'name': 'Praia do Valadão',
    'description': '',
    'address':
        'R. Francisco Benedito de Almeida, 86 - Centro, Guarapari - ES, 29200-060',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.667626,
    'longitude': -40.493155,
    'rating': 4.8,
  },
  {
    'name': 'Prainha De Muquiçaba',
    'description': '',
    'address':
        'Av. Camilo Gianordoli, 1329 - Muquiçaba, Guarapari - ES, 29215-080',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Muquiçaba',
    'latitude': -20.6626667,
    'longitude': -40.4971481,
    'rating': 4.6,
  },
  {
    'name': 'Praia dos padres',
    'description': '',
    'address': 'R. Onze - Balneário de Meaípe, Guarapari - ES, 29208-034',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Balneário de Meaípe',
    'latitude': -20.7360789,
    'longitude': -40.5339282,
    'rating': 4.7,
  },
  {
    'name': 'Praia da Rafinha',
    'description': '',
    'address': 'Av. Edízio Cirne, 60 - Centro, Guarapari - ES, 29200-080',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.671716,
    'longitude': -40.495881,
    'rating': 5.0,
  },
  {
    'name': 'Thermas International of Espírito Santo',
    'description': '',
    'address':
        'Rod. do Sol, s/n - Km 29 - Guarapari, Palmeiras - ES, 29220-730',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Park, Water park',
    'borough': 'Guarapari',
    'latitude': -20.5336089,
    'longitude': -40.3893325,
    'rating': 3.9,
  },
  {
    'name': 'Radium Hotel',
    'description': '',
    'address':
        'R. Simplício Almeida Rodrigues, 2 - Centro, Guarapari - ES, 29200-370',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Historical landmark',
    'borough': 'Centro',
    'latitude': -20.6741452,
    'longitude': -40.499671,
    'rating': 3.9,
  },
  {
    'name': 'Monumento Natural Pedra dos Dois Budas',
    'description': '',
    'address': 'Praia do Ermitão - Praia do Morro, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6574146,
    'longitude': -40.4668441,
    'rating': 4.9,
  },
  {
    'name':
        'Igreja Antiga Matriz Nossa Senhora da Conceição - Centro Histórico',
    'description': '',
    'address':
        'Ladeira Salvador Souza, 1585 - Centro, Guarapari - ES, 29200-090',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Catholic church',
    'borough': 'Centro',
    'latitude': -20.6681877,
    'longitude': -40.494916,
    'rating': 4.8,
  },
  {
    'name': 'Arpoador de Guaraparis',
    'description': '',
    'address': 'Av. Edízio Cirne, 60 - Centro, Guarapari - ES, 29200-080',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.6716953,
    'longitude': -40.4960279,
    'rating': null,
  },
  {
    'name': 'Praia do moro',
    'description': '',
    'address':
        'Parque da Areia Preta, Guarapari - State of Espírito Santo, 29200-260',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6738927,
    'longitude': -40.4999838,
    'rating': 4.4,
  },
  {
    'name': 'Orla de Lameirão',
    'description': '',
    'address': 'Estrada Virgílio Beiriz da Silva - Lameirão, ES, 29206-613',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.6904526,
    'longitude': -40.5241833,
    'rating': 4.8,
  },
  {
    'name': 'Praça da Paz',
    'description': '',
    'address': 'Av. Beira Mar - Praia do Morro, Guarapari - ES, 29216-010',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6519859,
    'longitude': -40.479153,
    'rating': 4.6,
  },
  {
    'name': 'Praia dos Pescadores',
    'description': '',
    'address': 'https://www.google.com/local/place/rap/edit/location?rg=true',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.7400982,
    'longitude': -40.5360565,
    'rating': 4.8,
  },
  {
    'name': 'Praia do Ermitão',
    'description':
        'A parkland trail leads to this rocky inlet with a crescent beach & a simple restaurant.',
    'address':
        'Parque Natural Municipal Morro da Pescaria - Praia do Morro, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Park',
    'borough': 'Praia do Morro',
    'latitude': -20.6571648,
    'longitude': -40.4689078,
    'rating': 4.7,
  },
  {
    'name': 'Cachoeira do Bravin',
    'description': '',
    'address': 'Guarapari São Felix, ES, 29227-350',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Todos os Santos',
    'latitude': -20.5316167,
    'longitude': -40.628994,
    'rating': 4.7,
  },
  {
    'name': 'Praia do Morro - Marlin Azul',
    'description': '',
    'address': 'Praia do Morro, Guarapari - State of Espírito Santo, 29216-010',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6524892,
    'longitude': -40.4787595,
    'rating': 4.7,
  },
  {
    'name': 'Casa de Vidro Guarapari',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.619252,
    'longitude': -40.551272,
    'rating': 4.7,
  },
  {
    'name': 'Praia do Urubu',
    'description': '',
    'address': 'R. João Serafim dos Anjos - Guarapari, ES, 29208-003',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.74178,
    'longitude': -40.5365007,
    'rating': 4.8,
  },
  {
    'name': 'Pedra do Mero',
    'description': '',
    'address':
        'Av. Manoel Rodrigues Pinheiro, 1109 - Setiba, Guarapari - ES, 29222-370',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Setiba',
    'latitude': -20.6341218,
    'longitude': -40.4414191,
    'rating': 5.0,
  },
  {
    'name': 'Creek Beach',
    'description':
        'No-frills beach offering a sandy shoreline, waves & fishing spots, plus a hike-&-bike promenade.',
    'address': 'Rod. Paulo Borges - Praia do Riacho, Guarapari - ES, 29201-440',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach',
    'borough': 'Praia do Riacho',
    'latitude': -20.6826048,
    'longitude': -40.5053402,
    'rating': 4.5,
  },
  {
    'name': 'Pedra Consuelo',
    'description': '',
    'address': '8GRJ+XJ, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.6575782,
    'longitude': -40.4684845,
    'rating': 4.9,
  },
  {
    'name': 'Praia da Estrela Morta',
    'description': '',
    'address': 'Av. Manoel Rodrigues Pinheiro - Una, Guarapari - ES, 29222-560',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Una',
    'latitude': -20.6363219,
    'longitude': -40.4485568,
    'rating': 5.0,
  },
  {
    'name': 'Tico tera',
    'description': '',
    'address': 'Centro, Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Centro',
    'latitude': -20.6846248,
    'longitude': -40.4990052,
    'rating': 5.0,
  },
  {
    'name': 'Praia da Cerca',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.6526729,
    'longitude': -40.4723889,
    'rating': 4.3,
  },
  {
    'name': 'Três Praias - 2ª Praia: Praia do Ancoradouro',
    'description': '',
    'address': '9G7J+CC, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.6363872,
    'longitude': -40.4689426,
    'rating': 4.9,
  },
  {
    'name': 'Prainha do Sul',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.6598392,
    'longitude': -40.4717469,
    'rating': 4.8,
  },
  {
    'name': 'Praia Bacutia',
    'description': '',
    'address': 'Alameda Frisia, 110 - Enseada Azul, Guarapari - ES, 29206-140',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.7331109,
    'longitude': -40.529977,
    'rating': 4.8,
  },
  {
    'name': 'Coralzinho',
    'description': '',
    'address':
        'Condomínio Edificio Aguas Marinhas - Av. Viña Del Mar, 1 - Enseada Azul, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Park',
    'borough': 'Enseada Azul',
    'latitude': -20.7218176,
    'longitude': -40.523532,
    'rating': 4.6,
  },
  {
    'name': 'Wakeboard',
    'description': '',
    'address': 'Praia do Morro, Guarapari - State of Espírito Santo, 29216-705',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6480702,
    'longitude': -40.483454,
    'rating': 5.0,
  },
  {
    'name': 'Praia de São Pedro',
    'description': '',
    'address': 'Av. Beira Mar, 163-149 - Muquiçaba, Guarapari - ES, 29216-010',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Muquiçaba',
    'latitude': -20.6624506,
    'longitude': -40.4963082,
    'rating': null,
  },
  {
    'name': 'Setiba Pina',
    'description': '',
    'address': 'Av. Um - Praia de Setiba, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach',
    'borough': 'Praia de Setiba',
    'latitude': -20.6356216,
    'longitude': -40.4291538,
    'rating': 4.8,
  },
  {
    'name': 'Mirante da Pedra do elefante',
    'description': '',
    'address': 'Estrada artur arpini - Guarapari, ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.6102033,
    'longitude': -40.5342973,
    'rating': 4.5,
  },
  {
    'name': 'Pedras Bacutia / Peracanga',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.7349382,
    'longitude': -40.5265106,
    'rating': 4.7,
  },
  {
    'name': 'Flyboardcapixaba',
    'description': '',
    'address': 'Av. Beira Mar - Praia do Morro, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6550356,
    'longitude': -40.4735225,
    'rating': 5.0,
  },
  {
    'name': 'Rota da Ferradura (Segunda Entrada)',
    'description': '',
    'address': 'BR-101, 166 - Guarapari, ES, 29227-640',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.643385,
    'longitude': -40.558862,
    'rating': 5.0,
  },
  {
    'name': 'Pedra da Bacutia',
    'description': '',
    'address': 'Av. Viña Del Mar - Enseada Azul, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.7288152,
    'longitude': -40.5274102,
    'rating': 4.5,
  },
  {
    'name': 'Igreja Matriz Nossa Senhora da Conceição - Matriz do Centro',
    'description': '',
    'address': 'Av. Davino Mattos, s/n - Centro, Guarapari - ES, 29200-430',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Catholic church',
    'borough': 'Centro',
    'latitude': -20.670124,
    'longitude': -40.499642,
    'rating': 4.8,
  },
  {
    'name': 'Praia de Santa Mônica',
    'description': '',
    'address': 'R. Prefeita Santa Rita - Santa Mônica, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Santa Mônica',
    'latitude': -20.6235036,
    'longitude': -40.458739,
    'rating': 4.5,
  },
  {
    'name': 'Ilha Coutinho',
    'description': '',
    'address': 'Praia de Setiba, Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia de Setiba',
    'latitude': -20.6399182,
    'longitude': -40.4300101,
    'rating': 5.0,
  },
  {
    'name': 'Pedra do Grevão',
    'description': '',
    'address': '9H65+XV, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.6370796,
    'longitude': -40.4404728,
    'rating': 5.0,
  },
  {
    'name': 'Pedras das Singularidades',
    'description': '',
    'address': 'Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.7336513,
    'longitude': -40.5261813,
    'rating': 5.0,
  },
  {
    'name': 'Sítio Catavento Guarapari',
    'description': '',
    'address': 'Estr. Rota do Turismo - Guarapari, ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.5987021,
    'longitude': -40.4750058,
    'rating': null,
  },
  {
    'name': 'supermercado BH1',
    'description': '',
    'address': 'Av. Anchieta, 36 - Ipiranga, Guarapari - ES, 29201-010',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Ipiranga',
    'latitude': -20.6778535,
    'longitude': -40.5042462,
    'rating': 4.5,
  },
  {
    'name': 'Praia das Confissões',
    'description': '',
    'address': 'R. Seis - Guarapari, ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.7396503,
    'longitude': -40.5342688,
    'rating': 4.5,
  },
  {
    'name': 'Praia de Una',
    'description': '',
    'address': 'Av. Manoel Rodrigues Pinheiro - Una, Guarapari - ES, 29222-560',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Public beach',
    'borough': 'Una',
    'latitude': -20.6333709,
    'longitude': -40.4414604,
    'rating': 4.7,
  },
  {
    'name': 'Píer de Sant\'Ana - Praia de Meaípe',
    'description': '',
    'address':
        'R. Manoel Duarte Souza Matos, 412 - Meaípe, Guarapari - ES, 29208-050',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Meaípe',
    'latitude': -20.7394223,
    'longitude': -40.5366077,
    'rating': 4.8,
  },
  {
    'name': 'Praia da Península de Meaípe',
    'description': '',
    'address': 'R. Giovane Sechin, 112 - Meaípe, Guarapari - ES, 29208-130',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Meaípe',
    'latitude': -20.741023,
    'longitude': -40.534041,
    'rating': 5.0,
  },
  {
    'name': 'Praia de Setiba',
    'description': '',
    'address': 'Setiba, Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Setiba',
    'latitude': -20.6354161,
    'longitude': -40.4403251,
    'rating': 4.9,
  },
  {
    'name': 'Pedra do Greve',
    'description': '',
    'address': 'R. Vênus - Praia de Setiba, Guarapari - ES, 29222-260',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia de Setiba',
    'latitude': -20.640145,
    'longitude': -40.4314094,
    'rating': 5.0,
  },
  {
    'name': 'Praia do Jogo da Baleia',
    'description': '',
    'address':
        'R. Lúcio Rocha de Almeida - Enseada Azul, Guarapari - ES, 29206-270',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.729368,
    'longitude': -40.5217017,
    'rating': 4.5,
  },
  {
    'name': 'Ponto dos Gaúchos de Rio Grande/RS.',
    'description': '',
    'address':
        'Av. Antonio Ferreira De Araujo, 292 - Santa Mônica, Guarapari - ES, 29221-005',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Santa Mônica',
    'latitude': -20.6233955,
    'longitude': -40.4550076,
    'rating': 5.0,
  },
  {
    'name': 'Final da praia do morro',
    'description': '',
    'address': 'Av. Beira Mar, 42 - Praia do Morro, Guarapari - ES, 29208-700',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia do Morro',
    'latitude': -20.6522669,
    'longitude': -40.4813789,
    'rating': null,
  },
  {
    'name': 'Praia Secreta de Setibão',
    'description': '',
    'address': 'R. Berilo, 193 - Praia de Setiba, Guarapari - ES, 29222',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia de Setiba',
    'latitude': -20.6352737,
    'longitude': -40.4256974,
    'rating': 4.9,
  },
  {
    'name': 'SKY RACER ESCOLA DE VOO',
    'description': '',
    'address': 'Rod. Paulo Borges - Guarapari, ES, 29206-570',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.7016002,
    'longitude': -40.5151421,
    'rating': null,
  },
  {
    'name': 'Perocão',
    'description': '',
    'address': 'R. Marcelino Viêira, 20 - Perocão, Guarapari - ES, 29220-710',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Perocão',
    'latitude': -20.6261513,
    'longitude': -40.4687069,
    'rating': 5.0,
  },
  {
    'name': 'Buraco da velha',
    'description': '',
    'address': 'Perocão, Guarapari - State of Espírito Santo, 29220-513',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Perocão',
    'latitude': -20.6229866,
    'longitude': -40.4681821,
    'rating': null,
  },
  {
    'name': 'Mirante da Amora',
    'description': '',
    'address': 'R. Vênus - Praia de Setiba, Guarapari - ES, 29222-260',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia de Setiba',
    'latitude': -20.6385013,
    'longitude': -40.4318593,
    'rating': null,
  },
  {
    'name': 'Peracanga- Enseada azul',
    'description': '',
    'address': 'Av. Viña Del Mar - Enseada Azul, Guarapari - ES, 29208-440',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.7321117,
    'longitude': -40.5491827,
    'rating': 4.8,
  },
  {
    'name': 'Poço do Paredão',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.6301733,
    'longitude': -40.5703633,
    'rating': null,
  },
  {
    'name': 'Toca do Rock',
    'description': '',
    'address': 'Av. da Vitória - Santa Mônica, Guarapari - ES, 29221-530',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Santa Mônica',
    'latitude': -20.616842,
    'longitude': -40.4518395,
    'rating': null,
  },
  {
    'name': 'Lagoa de Sant\'Ana',
    'description': '',
    'address': 'Guarapari, State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Guarapari',
    'latitude': -20.7429143,
    'longitude': -40.5352405,
    'rating': 5.0,
  },
  {
    'name': 'Estreito Dan Dan',
    'description': '',
    'address': '9H65+XV, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.636556,
    'longitude': -40.440358,
    'rating': 5.0,
  },
  {
    'name': 'Baixa Mibra',
    'description': '',
    'address': '7FWQ+95, Guarapari - ES',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.7040378,
    'longitude': -40.5120689,
    'rating': 5.0,
  },
  {
    'name': 'Praia Alair & Cia',
    'description': '',
    'address':
        'Av. Viña Del Mar, 1214 - Enseada Azul, Guarapari - ES, 29206-170',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.7303353,
    'longitude': -40.5280112,
    'rating': null,
  },
  {
    'name': 'Acesso a praia do estaleiro',
    'description': '',
    'address': 'R. do Estaleiro, 299 - Perocão, Guarapari - ES, 29220',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Perocão',
    'latitude': -20.625022,
    'longitude': -40.465563,
    'rating': null,
  },
  {
    'name': 'Rochas da Matriz Dilatada',
    'description': '',
    'address': 'Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'None',
    'latitude': -20.7442412,
    'longitude': -40.5351627,
    'rating': null,
  },
  {
    'name': 'Sítio Morro do Balaio',
    'description': '',
    'address':
        'Estrada Alberto Pinto da Conceição, km 2,5 - Guarapari, ES, 29227-530',
    'category': 'hotels',
    'subtypes':
        'Tourist attraction, Event management company, Festival hall, Hiking area, Park, Restaurant, Rock climbing, Hotel',
    'borough': 'Guarapari',
    'latitude': -20.6121705,
    'longitude': -40.5344363,
    'rating': 4.8,
  },
  {
    'name': 'Praia do Cipó',
    'description': '',
    'address':
        'Praia do Cipó - Av. Manoel Rodrigues Pinheiro - Setiba, Guarapari - ES, 29222-350',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Setiba',
    'latitude': -20.6370154,
    'longitude': -40.4466494,
    'rating': 5.0,
  },
  {
    'name': 'Forte de Meaípe',
    'description': '',
    'address':
        'Av. Manoel Santana, 5 - Balneário de Meaípe, Guarapari - ES, 29208-010',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Balneário de Meaípe',
    'latitude': -20.7402152,
    'longitude': -40.5375266,
    'rating': null,
  },
  {
    'name': 'Résidencia Ecológico Pedra do Elefante',
    'description': '',
    'address':
        'Estrada Buenos Aires 2,7km - Buenos Aires, Guarapari - ES, 29227-550',
    'category': 'attractions',
    'subtypes': 'Tourist attraction, Hotel, Inn',
    'borough': 'Guarapari',
    'latitude': -20.6098791,
    'longitude': -40.5345801,
    'rating': 4.6,
  },
  {
    'name': 'Praia das Pousadas',
    'description': '',
    'address': 'Praia de Setiba, Guarapari - State of Espírito Santo',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Praia de Setiba',
    'latitude': -20.6388505,
    'longitude': -40.4310728,
    'rating': 4.8,
  },
  {
    'name': 'Praia de Graçaí ou Praia do Buzo',
    'description': '',
    'address':
        'R. Lúcio Rocha de Almeida - Enseada Azul, Guarapari - ES, 29206-270',
    'category': 'attractions',
    'subtypes': 'Tourist attraction',
    'borough': 'Enseada Azul',
    'latitude': -20.7280344,
    'longitude': -40.5215233,
    'rating': 5.0,
  },
  {
    'name': 'Restaurante Salino Guarapari',
    'description': '',
    'address':
        'Rua Joaquim Pereira De Almeida 40 Ed. Acquamarine - Centro, Guarapari - ES, 29200-080',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Brazilian restaurant',
    'borough': 'Centro',
    'latitude': -20.6710774,
    'longitude': -40.4963756,
    'rating': 4.4,
  },
  {
    'name': 'Carvoeiro Brasa & Bar',
    'description': '',
    'address':
        'R. Simplício Almeida Rodrigues, 100 - Centro, Guarapari - ES, 29200-370',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6737763,
    'longitude': -40.498869,
    'rating': 4.7,
  },
  {
    'name': 'Food Hall Beach',
    'description': '',
    'address':
        'R. Angélica Lucarelli Amaral, 5 - Centro, Guarapari - ES, 29200-390',
    'category': 'restaurants',
    'subtypes':
        'Japanese restaurant, Brewery, Delivery service, Authentic Japanese restaurant, Meal delivery, Pizza delivery, Pizza restaurant, Pizza takeaway',
    'borough': 'Centro',
    'latitude': -20.675008,
    'longitude': -40.5001977,
    'rating': 4.6,
  },
  {
    'name': 'Casa Marracini',
    'description': '',
    'address':
        'R. Fernando de Abreu, 121 - São Judas Tadeu, Guarapari - ES, 29200-490',
    'category': 'restaurants',
    'subtypes': 'Italian restaurant, Restaurant',
    'borough': 'São Judas Tadeu',
    'latitude': -20.6736004,
    'longitude': -40.5029061,
    'rating': 4.6,
  },
  {
    'name': 'Sabor Rural - Restaurante Comida Caseira',
    'description': '',
    'address':
        'Novo canal - R. José Barcelos de Matos - Parque da Areia Preta, Guarapari - ES, 29200-000',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Chop bar, Event venue',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6712208,
    'longitude': -40.5034585,
    'rating': 4.7,
  },
  {
    'name': 'Chão de Estrelas Restaurante',
    'description': '',
    'address': 'R. Getúlio Vargas, 161 - Centro, Guarapari - ES, 29200-180',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant',
    'borough': 'Centro',
    'latitude': -20.6693589,
    'longitude': -40.4970505,
    'rating': 4.4,
  },
  {
    'name': 'Kamillu\'s Gastronomia',
    'description': '',
    'address':
        'R. Pedro Caetano, 328 - Parque da Areia Preta, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.672945,
    'longitude': -40.4997215,
    'rating': 4.4,
  },
  {
    'name': 'Restaurante Divino Sabor - Restaurante Self-service',
    'description': '',
    'address':
        'R. Zuleima Fortes Farias, 143 - Centro, Guarapari - ES, 29200-600',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant',
    'borough': 'Centro',
    'latitude': -20.6721656,
    'longitude': -40.499672,
    'rating': 4.6,
  },
  {
    'name': 'Maria\'s Restaurante',
    'description': '',
    'address': 'R. Pedro Caetano, 159 - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6720464,
    'longitude': -40.4986803,
    'rating': 4.3,
  },
  {
    'name': 'Restaurante Katakas',
    'description': '',
    'address':
        'R. Ver. Ozias Santana, 690 - Morro Atalaia, Guarapari - ES, 29200-030',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Morro Atalaia',
    'latitude': -20.6655819,
    'longitude': -40.4951307,
    'rating': 4.3,
  },
  {
    'name': 'Restaurante Sol e Mar',
    'description': '',
    'address': 'Av. Anchieta, N° 47 - Ipiranga, Guarapari - ES, 29201-010',
    'category': 'restaurants',
    'subtypes': 'Chicken restaurant, Takeout restaurant, Restaurant',
    'borough': 'Ipiranga',
    'latitude': -20.6776103,
    'longitude': -40.5042449,
    'rating': 4.3,
  },
  {
    'name': 'Restaurante Cheiro Verde Guarapari',
    'description': '',
    'address': 'R. Getúlio Vargas, 124 - Centro, Guarapari - ES, 29200-180',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.669116,
    'longitude': -40.4971691,
    'rating': 4.4,
  },
  {
    'name': 'Restaurante Bom Paladar',
    'description': '',
    'address':
        'R. Zuleima Fortes Farias, 133 - Parque da Areia Preta, Guarapari - ES, 29200-600',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6721403,
    'longitude': -40.4996195,
    'rating': 4.6,
  },
  {
    'name': 'Central Self Service',
    'description': '',
    'address': 'R. Pedro Caetano, 250 - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant',
    'borough': 'Centro',
    'latitude': -20.6723704,
    'longitude': -40.4991772,
    'rating': 4.4,
  },
  {
    'name': 'Cozinha do Baiano- Beco da Fome',
    'description': '',
    'address': 'Beco da Fome, Centro - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.672239,
    'longitude': -40.4974978,
    'rating': 3.8,
  },
  {
    'name': 'Restaurante Benfica',
    'description': '',
    'address': 'R. Henrique Coutinho, 16 - Centro, Guarapari - ES, 29200-190',
    'category': 'restaurants',
    'subtypes': 'Brazilian restaurant',
    'borough': 'Centro',
    'latitude': -20.670807,
    'longitude': -40.4965101,
    'rating': 4.2,
  },
  {
    'name': 'Restaurante Deck Guarapari',
    'description': '',
    'address':
        'Travessa Palmerindo de Souza - Centro, Guarapari - ES, 29200-600',
    'category': 'restaurants',
    'subtypes': 'Brazilian restaurant',
    'borough': 'Centro',
    'latitude': -20.6718021,
    'longitude': -40.4978984,
    'rating': 4.0,
  },
  {
    'name': 'Cantinho do Bacalhau',
    'description': '',
    'address': 'Av. Edízio Cirne, 54 - Centro, Guarapari - ES, 29200-080',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6710803,
    'longitude': -40.496283,
    'rating': 4.3,
  },
  {
    'name': 'Dal Mare Restaurante',
    'description': '',
    'address': 'Av. Praiana, 1076 - Praia do Morro, Guarapari - ES, 29216-090',
    'category': 'restaurants',
    'subtypes': 'Seafood restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6525274,
    'longitude': -40.4873816,
    'rating': 4.6,
  },
  {
    'name': 'Cozinha da Vó Quitéria',
    'description': '',
    'address':
        'R. Manoel Severo Simões, 120 - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6721817,
    'longitude': -40.4984757,
    'rating': 4.4,
  },
  {
    'name': 'Restaurante Maná',
    'description': '',
    'address':
        'R Jacinto de Almeida, 199-61 - Parque da Areia Preta, Guarapari - ES, 29202-500',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6714648,
    'longitude': -40.5022543,
    'rating': 4.9,
  },
  {
    'name': 'Sabor e Cia',
    'description': '',
    'address': 'R. Augusto de Mattos, 27 - Centro, Guarapari - ES, 29200-310',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.669339,
    'longitude': -40.4983362,
    'rating': 4.3,
  },
  {
    'name': 'Tarboush Express - comida árabe',
    'description': '',
    'address':
        'R. Mercedes Costa Pimentel, 44 - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Middle Eastern restaurant',
    'borough': 'Centro',
    'latitude': -20.6700513,
    'longitude': -40.4978317,
    'rating': 4.6,
  },
  {
    'name': 'La Casa Beer Bar e Restaurante',
    'description': '',
    'address':
        'R. Joaquim Augusto Ribeiro de Castro - Centro, Guarapari - ES, 29200-160',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.66877,
    'longitude': -40.4984517,
    'rating': 4.7,
  },
  {
    'name': 'Informal',
    'description': '',
    'address':
        'Av. Des. Lourival de Almeida - Centro, Guarapari - ES, 29200-250',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Pizza restaurant',
    'borough': 'Centro',
    'latitude': -20.6717997,
    'longitude': -40.4970625,
    'rating': 3.9,
  },
  {
    'name': 'Loretis Gourmet',
    'description': '',
    'address':
        'Nosso WhatsApp 28999893786 - R. Santana do Iapó, 348 - Muquiçaba, Guarapari - ES, 29215-020',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Muquiçaba',
    'latitude': -20.6630171,
    'longitude': -40.5002526,
    'rating': 4.5,
  },
  {
    'name': 'Kibe Lanches',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 208 - Centro, Guarapari - ES, 29200-260',
    'category': 'restaurants',
    'subtypes': 'Middle Eastern restaurant, Fast food restaurant',
    'borough': 'Centro',
    'latitude': -20.6719297,
    'longitude': -40.4980901,
    'rating': 4.5,
  },
  {
    'name': 'Yaki Hot - Sushi',
    'description': '',
    'address':
        'Praia das Castanheiras - Av. Des. Lourival de Almeida, 202 - loja 02 - Centro, Guarapari - ES, 29200-250',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Japanese restaurant',
    'borough': 'Centro',
    'latitude': -20.6730304,
    'longitude': -40.4976592,
    'rating': 4.5,
  },
  {
    'name':
        'Costella\'s - Bar & Restaurante Self-Service | Frango Assado do Zainho',
    'description': '',
    'address':
        'Av. José Barcellos de Mattos, 35 - Parque Areia Preta - Centro, Guarapari - ES, 29200-168',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant, Bar & grill',
    'borough': 'Centro',
    'latitude': -20.6705872,
    'longitude': -40.5008311,
    'rating': 4.4,
  },
  {
    'name': 'Yasu Sushi Bar Guarapari',
    'description': '',
    'address':
        'R. Mercedes Costa Pimentel, n° 100 - Centro, Guarapari - ES, 29200-285',
    'category': 'Restaurante de sushi',
    'subtypes': 'Sushi restaurant',
    'borough': 'Centro',
    'latitude': -20.6705889,
    'longitude': -40.4977774,
    'rating': 4.6,
  },
  {
    'name': 'Ika Poke',
    'description': '',
    'address':
        'Beco da Copesa - final da rua - R. Joaquim Augusto Ribeiro de Castro, 100 - Centro, Guarapari - ES, 29200-130',
    'category': 'Restaurante havaiano',
    'subtypes': 'Hawaiian restaurant, Japanized western restaurant',
    'borough': 'Centro',
    'latitude': -20.6666972,
    'longitude': -40.4965882,
    'rating': 4.1,
  },
  {
    'name': 'Restaurante Gramado',
    'description': '',
    'address':
        'R Jacinto de Almeida - Parque da Areia Preta, Guarapari - ES, 29200-045',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6713393,
    'longitude': -40.5014745,
    'rating': 4.6,
  },
  {
    'name': 'Bar & Restaurant Valdecy',
    'description': '',
    'address':
        'R. José Barcelos de Matos - Parque da Areia Preta, Guarapari - ES, 29200-270',
    'category': 'bars',
    'subtypes': 'Restaurant, Bar',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6712703,
    'longitude': -40.5034077,
    'rating': 4.6,
  },
  {
    'name': 'Restaurante Pratão Capixaba',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 1248 - Aeroporto, Guarapari - ES, 29216-705',
    'category': 'restaurants',
    'subtypes': 'Buffet restaurant, Brazilian restaurant',
    'borough': 'Aeroporto',
    'latitude': -20.6451561,
    'longitude': -40.4880761,
    'rating': 4.5,
  },
  {
    'name': 'Brasa Meat Praia - Beco da Fome',
    'description': '',
    'address': 'Beco da Fome, 40 - loja 05 - Centro, Guarapari - ES, 29200-055',
    'category': 'Hamburgueria',
    'subtypes': 'Hamburger restaurant',
    'borough': 'Centro',
    'latitude': -20.6720916,
    'longitude': -40.4975114,
    'rating': 4.2,
  },
  {
    'name': 'Espetaria Steak Mix',
    'description': '',
    'address':
        'Av.Joaquim da Silva Lima, Beco da Fome, 207 - loja 7 - Centro, Guarapari - ES, 29200-260',
    'category': 'restaurants',
    'subtypes': 'Grill, Diner, Food court, Pizza restaurant',
    'borough': 'Centro',
    'latitude': -20.6720713,
    'longitude': -40.4976942,
    'rating': 4.3,
  },
  {
    'name': 'Sabores Express',
    'description': '',
    'address':
        'Av. Des. Lourival de Almeida, 85 - Centro, Guarapari - ES, 29200-250',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6716762,
    'longitude': -40.4968993,
    'rating': 4.3,
  },
  {
    'name': 'Espetão Paris - Centro',
    'description': '',
    'address': 'R. Augusto de Mattos, 27 - Centro, Guarapari - ES, 29200-310',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6693081,
    'longitude': -40.4983616,
    'rating': 4.4,
  },
  {
    'name': 'Franguinho Saúde | Restaurante - Lanchonete - Pizzaria - Caldos',
    'description': '',
    'address':
        'R. Paulo Aguiar, 33 - Parque da Areia Preta, Guarapari - ES, 29200-630',
    'category': 'restaurants',
    'subtypes': 'Chicken restaurant, Fast food restaurant, Snack bar',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6708123,
    'longitude': -40.500874,
    'rating': 4.5,
  },
  {
    'name': 'Le Cave Pizzaria',
    'description': '',
    'address': 'Av. Praiana, 1140 - Praia do Morro, Guarapari - ES, 29216-090',
    'category': 'restaurants',
    'subtypes': 'Pizza restaurant, Restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6519908,
    'longitude': -40.4859636,
    'rating': 4.4,
  },
  {
    'name': 'Aroma Gastronomia',
    'description': '',
    'address':
        'Av. Pedro Ramos, 118 - Parque da Areia Preta, Guarapari - ES, 29200-700',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6711879,
    'longitude': -40.505834,
    'rating': 4.0,
  },
  {
    'name': 'Restaurante Tempero Divino',
    'description': '',
    'address': 'R. Pedro Caetano, 21 - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6715445,
    'longitude': -40.4981586,
    'rating': 3.7,
  },
  {
    'name': 'Recanto da Zezé 2',
    'description': '',
    'address': 'Praia das Castanheiras - Guarapari, ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Guarapari',
    'latitude': -20.6743259,
    'longitude': -40.4976275,
    'rating': 4.1,
  },
  {
    'name': 'Mangaba Restô Bar Praia do Morro',
    'description': '',
    'address': 'Av. Praiana, 20 - Praia do Morro, Guarapari - ES, 29216-090',
    'category': 'bars',
    'subtypes':
        'Restaurant, Beer hall, Brewery, Live music bar, Night club, Pub, Cocktail bar',
    'borough': 'Praia do Morro',
    'latitude': -20.6551214,
    'longitude': -40.4916496,
    'rating': 4.4,
  },
  {
    'name': 'Mister Kafta',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 207 - Centro, Guarapari - ES, 29200-260',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6719905,
    'longitude': -40.4977801,
    'rating': 4.2,
  },
  {
    'name': 'Senhor Yaki - Japa de Balcão',
    'description': '',
    'address':
        'Edifício Caribe - R. Mercedes Costa Pimentel, 44 - loja 12b - Centro, Guarapari - ES, 29200-285',
    'category': 'restaurants',
    'subtypes': 'Japanese restaurant, Japanized western restaurant',
    'borough': 'Centro',
    'latitude': -20.6700209,
    'longitude': -40.4978437,
    'rating': 5.0,
  },
  {
    'name': 'Lenita',
    'description': '',
    'address': 'Av. Oceânica, 97 - Praia do Morro, Guarapari - ES, 29216-080',
    'category': 'restaurants',
    'subtypes': 'Family restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6512154,
    'longitude': -40.4762387,
    'rating': 4.7,
  },
  {
    'name': 'Filet Bar e Restaurante',
    'description': '',
    'address': 'Av. Praiana, 1229 - Praia do Morro, Guarapari - ES, 29216-090',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Grill, Bar, Salad shop, Self service restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6524395,
    'longitude': -40.4867706,
    'rating': 4.5,
  },
  {
    'name': 'Leblon 145 Parrilla Bar',
    'description': '',
    'address':
        'R. Antônio Sobreiro, 145 - Praia do Morro, Guarapari - ES, 29216-185',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Cocktail bar, Live music bar',
    'borough': 'Praia do Morro',
    'latitude': -20.6548515,
    'longitude': -40.4947988,
    'rating': 4.8,
  },
  {
    'name': 'Oficina de Sabores',
    'description': '',
    'address': 'R. Pedro Caetano, 132 - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.671816,
    'longitude': -40.4986604,
    'rating': 5.0,
  },
  {
    'name': 'Kymai Sushi',
    'description': '',
    'address':
        'R. Otávio Manhães de Andrade, 126 - Centro, Guarapari - ES, 29200-450',
    'category': 'Sushi para viagem',
    'subtypes':
        'Sushi takeaway, Japanese restaurant, Raw food restaurant, Sushi restaurant',
    'borough': 'Centro',
    'latitude': -20.6740477,
    'longitude': -40.5008143,
    'rating': 4.9,
  },
  {
    'name': 'Alecrim Forneria & Pastifício',
    'description': '',
    'address':
        'WhatsApp on-line, edifício dom Luiz Felipe - R. Henrique Coutinho, 16 - loja 01 - Centro, Guarapari - ES, 29200-190',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.670904,
    'longitude': -40.4963096,
    'rating': 4.6,
  },
  {
    'name': 'Good Burguer Casa Do Hambúrguer',
    'description': '',
    'address':
        'R. Antônio Cláudio Coutinho, 416 - sao judas, Guarapari - ES, 29201-115',
    'category': 'Lanchonete',
    'subtypes': 'Snack bar, Fast food restaurant, Hamburger restaurant',
    'borough': 'sao judas',
    'latitude': -20.6763257,
    'longitude': -40.5038726,
    'rating': 4.5,
  },
  {
    'name': 'Zona Sul - Burguers e Gourmets em Guarapari',
    'description': '',
    'address':
        'WhatsApp on-line - R Jacinto de Almeida, 124 (27 - 99511-2662 - Independência, Guarapari - ES, 29200-695',
    'category': 'restaurants',
    'subtypes': 'Pizza restaurant, Hamburger restaurant, Snack bar',
    'borough': 'Independência',
    'latitude': -20.671384,
    'longitude': -40.5013897,
    'rating': 4.6,
  },
  {
    'name': 'Restaurante Self Service Cariocas',
    'description': '',
    'address':
        'Tv. Custódio Gonçalves dos Santos, 15 - Centro, Guarapari - ES, 29200-280',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6697411,
    'longitude': -40.4975499,
    'rating': 5.0,
  },
  {
    'name': 'Loreti\'s Grill',
    'description': '',
    'address': 'BR-101 - Guarapari, ES, 29215-640',
    'category': 'restaurants',
    'subtypes': 'Barbecue restaurant, Bed & breakfast, Beer hall, Tapas bar',
    'borough': 'Guarapari',
    'latitude': -20.6347556,
    'longitude': -40.5403964,
    'rating': 4.3,
  },
  {
    'name': 'Family Burger',
    'description': '',
    'address':
        'R. Antônio Cláudio Coutinho, 355 - loja 03 - Ipiranga, Guarapari - ES, 29200-115',
    'category': 'Hamburgueria',
    'subtypes': 'Hamburger restaurant',
    'borough': 'Ipiranga',
    'latitude': -20.6762371,
    'longitude': -40.5034202,
    'rating': 4.6,
  },
  {
    'name': 'Bob\'s Burger - Shopping Guarapari',
    'description': '',
    'address':
        'Av. Dr. Roberto Calmon, 140 - Centro, Guarapari - ES, 29200-292',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Fast food restaurant',
    'borough': 'Centro',
    'latitude': -20.6705599,
    'longitude': -40.4984636,
    'rating': 4.1,
  },
  {
    'name': 'Restaurante Gaeta',
    'description': '',
    'address': 'Av. Beira Mar, 47 - Meaípe, Guarapari - ES, 29208-010',
    'category': 'restaurants',
    'subtypes': 'Seafood restaurant',
    'borough': 'Meaípe',
    'latitude': -20.738413,
    'longitude': -40.537938,
    'rating': 4.6,
  },
  {
    'name': 'Subway',
    'description':
        'Casual counter-serve chain for build-your-own sandwiches & salads, with health-conscious options.',
    'address':
        'Av. Joaquim da Silva Lima, 23 - Centro, Guarapari - ES, 29200-260',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6713102,
    'longitude': -40.4971843,
    'rating': 4.3,
  },
  {
    'name': 'Mr. Fritz Guarapari | Frango Frito',
    'description': '',
    'address':
        'R. Manoel Severo Simões, 120 - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Fast food restaurant',
    'borough': 'Centro',
    'latitude': -20.673432,
    'longitude': -40.4983748,
    'rating': 4.7,
  },
  {
    'name': 'Centro Gourment Bom Peix',
    'description': '',
    'address': 'R. Manoel Severo Simões - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6734932,
    'longitude': -40.4984464,
    'rating': null,
  },
  {
    'name': 'Ze Coxinha Guarapari',
    'description': '',
    'address': 'R. Getúlio Vargas, 241 - Centro, Guarapari - ES, 29200-180',
    'category': 'restaurants',
    'subtypes': 'Fast food restaurant',
    'borough': 'Centro',
    'latitude': -20.6702327,
    'longitude': -40.4969194,
    'rating': 4.2,
  },
  {
    'name': 'Temakeria Filadelfia',
    'description': '',
    'address': 'R. F, 66 - Parque da Areia Preta, Guarapari - ES, 29200-720',
    'category': 'restaurants',
    'subtypes': 'Japanese restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6719548,
    'longitude': -40.5069119,
    'rating': 4.4,
  },
  {
    'name': 'Palicone Steak House Guarapari',
    'description': '',
    'address': 'Beco da Fome - Centro, Guarapari - ES, 29200-055',
    'category': 'restaurants',
    'subtypes': 'Meat dish restaurant',
    'borough': 'Centro',
    'latitude': -20.6721638,
    'longitude': -40.4973841,
    'rating': null,
  },
  {
    'name': 'SP Massas Artesanais',
    'description': '',
    'address':
        'R. Henrique Coutinho, 34 - loja 3 - Centro, Guarapari - ES, 29200-190',
    'category': 'Loja de massas',
    'subtypes': 'Restaurant, Frozen food store, Italian restaurant, Pasta shop',
    'borough': 'Centro',
    'latitude': -20.6703073,
    'longitude': -40.4963943,
    'rating': 5.0,
  },
  {
    'name': 'Domino\'s Pizza',
    'description':
        'Delivery/carryout chain offering a wide range of pizzas & a variety of other dishes & sides.',
    'address':
        'R. Manoel Severo Simões, 125 - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Pizza restaurant, Pizza delivery',
    'borough': 'Centro',
    'latitude': -20.6734532,
    'longitude': -40.4982483,
    'rating': 4.3,
  },
  {
    'name': 'QUIOSQUE DA EURA',
    'description': '',
    'address':
        'Av. Des. Lourival de Almeida, quiosque numero 5 - Centro, Guarapari - ES, 29200-250',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6743495,
    'longitude': -40.497651,
    'rating': 4.5,
  },
  {
    'name':
        'Pancakes | Hamburgueria & Panquecaria | Panquecas, Hambúrgueres Artesanais, Crepiocas, Tapiocas e outros.',
    'description': '',
    'address':
        'Ed. Palmares - Beco da Fome, Av. Joaquim da Silva Lima, 207 - Lj. 06 - Centro, Guarapari - ES, 29200-260',
    'category': 'Hamburgueria',
    'subtypes':
        'Hamburger restaurant, Creperie, Gluten-free restaurant, Lunch restaurant, Pancake restaurant, Tapas bar',
    'borough': 'Centro',
    'latitude': -20.6720646,
    'longitude': -40.4978076,
    'rating': 3.7,
  },
  {
    'name': 'Chef Lucho Brasil',
    'description': '',
    'address': 'R. José Barcelos de Matos - Centro, Guarapari - ES, 29200-720',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6714252,
    'longitude': -40.5043183,
    'rating': null,
  },
  {
    'name': 'Mileto Espetos',
    'description': '',
    'address': 'Av. Paris, 737 - Praia do Morro, Guarapari - ES, 29216-570',
    'category': 'restaurants',
    'subtypes': 'Restaurant, Bar & grill, Pizza restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6446989,
    'longitude': -40.4825725,
    'rating': 4.7,
  },
  {
    'name': 'Fit Vibes - Marmitas Saudáveis em Guarapari',
    'description': '',
    'address':
        'Referencia: em frente a pizzaria Dominos, na lateral do hotel Coronado - R. Manoel Severo Simões, 120 - Loja 02 - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes':
        'Health food restaurant, Chicken shop, Nature preserve, Restaurant',
    'borough': 'Centro',
    'latitude': -20.6721817,
    'longitude': -40.4984757,
    'rating': null,
  },
  {
    'name': 'Becco 05',
    'description': '',
    'address':
        'Beco da Fome, Ed. Palmares - Av. Joaquim da Silva Lima, loja 05 - Centro, Guarapari - ES, 29200-260',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6721114,
    'longitude': -40.4976474,
    'rating': null,
  },
  {
    'name': 'Ali Baba E Os 40 Kibes',
    'description': '',
    'address': 'R. Getúlio Vargas, 272 - Centro, Guarapari - ES, 29200-180',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6700714,
    'longitude': -40.497127,
    'rating': 4.0,
  },
  {
    'name': 'Império do Frango',
    'description': '',
    'address':
        'R. Antônio Cláudio Coutinho, 335 - Ipiranga, Guarapari - ES, 29200-115',
    'category': 'restaurants',
    'subtypes': 'Chicken restaurant',
    'borough': 'Ipiranga',
    'latitude': -20.6736107,
    'longitude': -40.5014394,
    'rating': 3.8,
  },
  {
    'name': 'Tropical Smoothies',
    'description':
        'Casual, health-conscious chain cafe featuring custom smoothies, sandwiches & wraps.',
    'address':
        'R. Manoel Severo Simões, 65 - Centro, Guarapari - ES, 29200-265',
    'category': 'restaurants',
    'subtypes': 'Fast food restaurant',
    'borough': 'Centro',
    'latitude': -20.6730495,
    'longitude': -40.4981951,
    'rating': 4.5,
  },
  {
    'name': 'Mais Burger',
    'description': '',
    'address': 'R. Henrique Coutinho, 39 - Centro, Guarapari - ES, 29208-180',
    'category': 'Hamburgueria',
    'subtypes': 'Hamburger restaurant, Restaurant',
    'borough': 'Centro',
    'latitude': -20.6702612,
    'longitude': -40.4966482,
    'rating': 4.9,
  },
  {
    'name': 'Boleros Bar',
    'description': '',
    'address': 'Av. Edízio Cirne, 54 - Centro, Guarapari - ES, 29200-080',
    'category': 'bars',
    'subtypes': 'Restaurant, Bar',
    'borough': 'Centro',
    'latitude': -20.6710471,
    'longitude': -40.496376,
    'rating': 4.3,
  },
  {
    'name': 'Nonaka Bar and Snack Bar',
    'description': '',
    'address':
        'R. Horácio Santana, 468 - São Judas Tadeu, Guarapari - ES, 29200-750',
    'category': 'Lanchonete',
    'subtypes': 'Snack bar, Meal delivery, Restaurant',
    'borough': 'São Judas Tadeu',
    'latitude': -20.6732101,
    'longitude': -40.5056788,
    'rating': 4.7,
  },
  {
    'name': 'Casa di Massa',
    'description': '',
    'address':
        'Rua Francisco de Assis Santana, Rua do Trabalho, 50 Fundos, Guarapari - ES, 29200-420',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6708956,
    'longitude': -40.4990122,
    'rating': 5.0,
  },
  {
    'name': 'Churrasquinho do Amendoim',
    'description': '',
    'address':
        'Ao lado do mundo do açaí, no ypiranga - Av. Anchieta, 335 - Ipiranga, Guarapari - ES, 29200-115',
    'category': 'restaurants',
    'subtypes': 'Barbecue restaurant',
    'borough': 'Ipiranga',
    'latitude': -20.6759827,
    'longitude': -40.5036809,
    'rating': 5.0,
  },
  {
    'name': 'Hot Dog do Rique & Preto',
    'description': '',
    'address':
        'Praça Ciríaco Ramalhete de Oliveira - Centro, Guarapari - ES, 29200-360',
    'category': 'Cachorro-quente',
    'subtypes': 'Hot dog restaurant',
    'borough': 'Centro',
    'latitude': -20.6744121,
    'longitude': -40.497996,
    'rating': 4.9,
  },
  {
    'name': 'Kiosque Tia Regina',
    'description': '',
    'address': 'Praca Gov. Bley, 159 - Centro, Guarapari - ES, 29200-185',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.674436,
    'longitude': -40.4983246,
    'rating': 4.7,
  },
  {
    'name': 'Gugu Lanches I Ipiranga',
    'description': '',
    'address': 'Av. Anchieta, 423 - Ipiranga, Guarapari - ES, 29201-020',
    'category': 'Hamburgueria',
    'subtypes': 'Hamburger restaurant, Snack bar',
    'borough': 'Ipiranga',
    'latitude': -20.6768138,
    'longitude': -40.5042998,
    'rating': 4.3,
  },
  {
    'name': 'Restaurante De Xe Xéu',
    'description': '',
    'address': 'Av. Pedro Ramos, 123 - Centro, Guarapari - ES, 29200-172',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6700472,
    'longitude': -40.5006035,
    'rating': null,
  },
  {
    'name': 'Braseiro Gourmet',
    'description': '',
    'address':
        'anexo ao lava-jato Bruno Lyra - R. Pedro Caetano, s/n - Centro, Guarapari - ES, 29200-350',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.671939,
    'longitude': -40.4987623,
    'rating': null,
  },
  {
    'name': 'Burger King',
    'description':
        'Well-known fast-food chain serving grilled burgers, fries & shakes.',
    'address':
        'Av. Dr. Roberto Calmon, 140 - Centro, Guarapari - ES, 29200-340',
    'category': 'restaurants',
    'subtypes':
        'Fast food restaurant, Hamburger restaurant, Meal delivery, Restaurant',
    'borough': 'Centro',
    'latitude': -20.670628,
    'longitude': -40.4985123,
    'rating': 4.3,
  },
  {
    'name': 'Lanchonete Maria Gula',
    'description': '',
    'address':
        'R. Francisco de Assis Santana, 65 - Loja 03 - Centro, Guarapari - ES, 29200-420',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6702753,
    'longitude': -40.499981,
    'rating': 4.9,
  },
  {
    'name': 'Cantinho do Curuca',
    'description': '',
    'address': 'Av. Beira Mar, 96 - Meaípe, Guarapari - ES, 29208-180',
    'category': 'restaurants',
    'subtypes': 'Seafood restaurant',
    'borough': 'Meaípe',
    'latitude': -20.7380828,
    'longitude': -40.5386942,
    'rating': 4.6,
  },
  {
    'name': 'Rei do Espetinho',
    'description': '',
    'address': 'R. Getúlio Vargas, 130 - Centro, Guarapari - ES, 29200-180',
    'category': 'restaurants',
    'subtypes': 'Barbecue restaurant',
    'borough': 'Centro',
    'latitude': -20.6691839,
    'longitude': -40.4971715,
    'rating': 5.0,
  },
  {
    'name': 'Lamen Shop',
    'description': '',
    'address':
        'Rua José Barcellos de Mattos, 165 - São Judas Tadeu Guarapari - ES CEP:, 29200-720',
    'category': 'Restaurante de sushi',
    'subtypes': 'Sushi restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6708045,
    'longitude': -40.5011353,
    'rating': null,
  },
  {
    'name': 'Espeto Mineiro',
    'description': '',
    'address':
        'R. Carlos Santana - Parque da Areia Preta, Guarapari - ES, 29200-142',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6709957,
    'longitude': -40.5020088,
    'rating': 4.7,
  },
  {
    'name': 'Bosque de Setiba',
    'description': '',
    'address': 'Ville - R. Juiz de Fora - Setiba, Guarapari - ES, 29222-633',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Setiba',
    'latitude': -20.6175583,
    'longitude': -40.4382038,
    'rating': 4.5,
  },
  {
    'name': 'GARAGEN\'S LANCHONETE',
    'description': '',
    'address': 'Av. Anchieta - Ipiranga, Guarapari - ES, 29201-010',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Ipiranga',
    'latitude': -20.6761956,
    'longitude': -40.5033771,
    'rating': null,
  },
  {
    'name': 'Lanches do ABENCOADO',
    'description': '',
    'address': 'R. João Batista Lima, 164 - Centro, Guarapari - ES, 29200-330',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Centro',
    'latitude': -20.6714167,
    'longitude': -40.4984055,
    'rating': 5.0,
  },
  {
    'name': 'Terraço Guarapari',
    'description': '',
    'address':
        'R. Domingos Correia da Rocha - Perocão, Guarapari - ES, 29200-000',
    'category': 'Local para eventos',
    'subtypes': 'Restaurant, Inn, Event venue',
    'borough': 'Perocão',
    'latitude': -20.6181526,
    'longitude': -40.4710464,
    'rating': 4.5,
  },
  {
    'name': 'Casa da Figueira Café',
    'description': '',
    'address':
        'BR-101 - km 339, Estrada Rota da Ferradura - Jaboti, Guarapari - ES, 29227-640',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Guarapari',
    'latitude': -20.6428708,
    'longitude': -40.5592198,
    'rating': 4.7,
  },
  {
    'name': 'Cantinho Do Pastel',
    'description': '',
    'address':
        'R. José Barcelos de Matos, 151 - Parque da Areia Preta, Guarapari - ES, 29200-720',
    'category': 'restaurants',
    'subtypes': 'Restaurant',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6708875,
    'longitude': -40.5013669,
    'rating': null,
  },
  {
    'name': 'Sabores Café & Bistrô',
    'description': '',
    'address':
        'R. Otávio Manhães de Andrade, 45 - Centro, Guarapari - ES, 29200-450',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Centro',
    'latitude': -20.6741619,
    'longitude': -40.5010178,
    'rating': 4.6,
  },
  {
    'name': 'Café com Churros',
    'description': '',
    'address':
        'Ed. Garios - Av. Des. Lourival de Almeida, n° 100 - Loja 11 - Centro, Guarapari - ES, 29200-250',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop, Candy store, Churreria, Coffee store',
    'borough': 'Centro',
    'latitude': -20.6719791,
    'longitude': -40.4970626,
    'rating': 4.6,
  },
  {
    'name':
        'Empório Mineiro Cheirin Bão GUARAPARI - Cafés Especiais & Delícias Típicas',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 288 - Loja 02 - Centro, Guarapari - ES, 29200-260',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Centro',
    'latitude': -20.6727449,
    'longitude': -40.4988002,
    'rating': 4.3,
  },
  {
    'name': 'Ana\'s Coffee',
    'description': '',
    'address':
        'R. Pref. Epaminondas de Almeida, 61 - Parque da Areia Preta, Guarapari - ES, 29200-186',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6721395,
    'longitude': -40.5013243,
    'rating': 4.0,
  },
  {
    'name': 'Coffeebox',
    'description': '',
    'address':
        'Av. Praiana, 1192 - Loja 1 - Praia do Morro, Guarapari - ES, 29216-090',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Praia do Morro',
    'latitude': -20.6522065,
    'longitude': -40.4867301,
    'rating': 4.7,
  },
  {
    'name': 'Café Perim',
    'description': '',
    'address':
        'R. José Barcelos de Matos - Parque da Areia Preta, Guarapari - ES, 29200-720',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.671088,
    'longitude': -40.5036742,
    'rating': 5.0,
  },
  {
    'name': 'Gelateria e Café Dolce Freddo',
    'description': '',
    'address':
        'Edifício Hilal Center - Av. Joaquim da Silva Lima, 90 - Loja 09 - Centro, Guarapari - ES, 29200-260',
    'category': 'Sorveteria',
    'subtypes': 'Coffee shop, Ice cream shop',
    'borough': 'Centro',
    'latitude': -20.6713917,
    'longitude': -40.4976308,
    'rating': 4.7,
  },
  {
    'name': 'Emporio Cafeteria',
    'description': '',
    'address':
        'Ed. Residencial Paris - Av. Paris, 150 - loja 03 - Praia do Morro, Guarapari - ES, 29216-570',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop, Pastry shop, Snack bar',
    'borough': 'Praia do Morro',
    'latitude': -20.6504417,
    'longitude': -40.4792761,
    'rating': 4.9,
  },
  {
    'name': 'Emporio Goiano Cafeteria',
    'description': '',
    'address':
        'Condomínio do Edificio Varandas do Mar - 075, Av. Beira Mar, 1900 - 48 - Praia do Morro, Guarapari - ES',
    'category': 'cafes',
    'subtypes': 'Coffee shop, Cafe',
    'borough': 'Praia do Morro',
    'latitude': -20.6567927,
    'longitude': -40.4918939,
    'rating': 4.4,
  },
  {
    'name': 'Turiya Café e Cerâmica',
    'description': '',
    'address': 'R. Fernando Torres, 40 - Perocão, Guarapari - ES, 29221-245',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Perocão',
    'latitude': -20.6228744,
    'longitude': -40.4643111,
    'rating': 5.0,
  },
  {
    'name': 'Chocolá Chocolateria, Cafeteria e Açaiteria',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 354 - loja 05 - Centro, Guarapari - ES, 29200-260',
    'category': 'Loja de chocolates',
    'subtypes': 'Coffee shop, Chocolate shop, Ice cream shop',
    'borough': 'Centro',
    'latitude': -20.6734399,
    'longitude': -40.4994148,
    'rating': 5.0,
  },
  {
    'name': 'Kauê santos confeitaria',
    'description': '',
    'address':
        'R. Primeiro de Janeiro, CEP:, 56 - Kubitschek, Guarapari - ES, 29203-070',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Kubitschek',
    'latitude': -20.6797211,
    'longitude': -40.5145687,
    'rating': 5.0,
  },
  {
    'name': 'Princesa Bolos',
    'description': '',
    'address':
        'R. José Barcelos de Matos - Parque da Areia Preta, Guarapari - ES, 29200-720',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Parque da Areia Preta',
    'latitude': -20.6704529,
    'longitude': -40.4998982,
    'rating': 4.3,
  },
  {
    'name': 'Na Tábua - Cestas Café da Manhã e Tábua de Frios',
    'description': '',
    'address': 'R. Veneza - Praia do Morro, Guarapari - ES, 29216-310',
    'category': 'Delicatessen',
    'subtypes':
        'Coffee shop, Breakfast restaurant, Cheese shop, Deli, Espresso bar, Gift basket store, Ham shop, Novelty store, Winery',
    'borough': 'Praia do Morro',
    'latitude': -20.6478965,
    'longitude': -40.4863602,
    'rating': 5.0,
  },
  {
    'name': 'Shell Café',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 1449 - Praia do Morro, Guarapari - ES, 29216-005',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Praia do Morro',
    'latitude': -20.6476185,
    'longitude': -40.4899755,
    'rating': null,
  },
  {
    'name': 'Cafeteria Cafezin de Minas',
    'description': '',
    'address':
        'Av. Mar do Norte, 203 - Praia do Morro, Guarapari - ES, 29216-580',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'Praia do Morro',
    'latitude': -20.6438196,
    'longitude': -40.4823654,
    'rating': 4.3,
  },
  {
    'name': 'Vila Anunciatta Café e Chopp',
    'description': '',
    'address': 'Avenida Artur Arpini, Buenos Aires, Guarapari - ES, 29227-550',
    'category': 'restaurants',
    'subtypes': 'Coffee shop, Restaurant',
    'borough': 'Guarapari',
    'latitude': -20.5812686,
    'longitude': -40.5410144,
    'rating': 4.7,
  },
  {
    'name': 'John burger',
    'description': '',
    'address': 'Av. Brasil, 05 - São Gabriel, Guarapari - ES, 29213-430',
    'category': 'coffee shops',
    'subtypes': 'Coffee shop',
    'borough': 'São Gabriel',
    'latitude': -20.6431917,
    'longitude': -40.5178765,
    'rating': 5.0,
  },
  {
    'name': 'D\'Silva Cafeteria e Restaurante',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 1554 - Praia do Morro, Guarapari - ES, 29216-705',
    'category': 'restaurants',
    'subtypes': 'Coffee shop, Restaurant',
    'borough': 'Praia do Morro',
    'latitude': -20.6428354,
    'longitude': -40.4857975,
    'rating': 5.0,
  },
  {
    'name': '1000 Bocados',
    'description': '',
    'address':
        'Av. Ewerson de Abreu Sodré, 838 - Muquiçaba, Guarapari - ES, 29215-010',
    'category': 'Lanchonete',
    'subtypes': 'Coffee shop, Snack bar, Hamburger restaurant',
    'borough': 'Muquiçaba',
    'latitude': -20.6604015,
    'longitude': -40.4978179,
    'rating': 5.0,
  },
  {
    'name': 'Republic of Loaves Bakery',
    'description': '',
    'address':
        'R. Francisco Vieira Passos, 12 - Muquiçaba, Guarapari - ES, 29215-440',
    'category': 'Padaria',
    'subtypes': 'Bakery, Breakfast restaurant, Confectionery store',
    'borough': 'Muquiçaba',
    'latitude': -20.6580937,
    'longitude': -40.4970676,
    'rating': 4.2,
  },
  {
    'name': 'Café & Delícias - Padaria e Cafeteria',
    'description': '',
    'address':
        'R. Alarico dos Santos, 332 - Muquiçaba, Guarapari - ES, 29215-360',
    'category': 'Padaria',
    'subtypes': 'Coffee shop, Bakery',
    'borough': 'Muquiçaba',
    'latitude': -20.6560996,
    'longitude': -40.4999744,
    'rating': null,
  },
  {
    'name': 'Banco do Brazil - Guarapari Agency',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 550 - Centro, Guarapari - ES, 29200-370',
    'category': 'Banco',
    'subtypes': 'Bank, ATM',
    'borough': 'Centro',
    'latitude': -20.6743794,
    'longitude': -40.5007307,
    'rating': 4.1,
  },
  {
    'name': 'Banco Santander - Agência 3369 Guarapari',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 224 - Centro, Guarapari - ES, 29200-260',
    'category': 'Banco',
    'subtypes': 'Bank, ATM, Financial institution',
    'borough': 'Centro',
    'latitude': -20.6719739,
    'longitude': -40.4982456,
    'rating': 2.6,
  },
  {
    'name': 'Caixa Econômica Federal - Centro',
    'description': '',
    'address': 'R. Getúlio Vargas, 204 - Centro, Guarapari - ES, 29200-925',
    'category': 'Banco',
    'subtypes': 'Bank, ATM',
    'borough': 'Centro',
    'latitude': -20.6697741,
    'longitude': -40.4969235,
    'rating': 2.9,
  },
  {
    'name': 'Banco Itaú - Agência 1609',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 304 - Centro, Guarapari - ES, 29200-260',
    'category': 'Bank',
    'subtypes': 'Bank, ATM',
    'borough': 'Centro',
    'latitude': -20.672761,
    'longitude': -40.4989969,
    'rating': 4.1,
  },
  {
    'name': 'Banesfacil',
    'description': '',
    'address':
        'Av. Joaquim da Silva Lima, 323 - Centro, Guarapari - ES, 29200-260',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Centro',
    'latitude': -20.672889,
    'longitude': -40.4986823,
    'rating': 3.6,
  },
  {
    'name': 'Banestes',
    'description': '',
    'address': 'Beco da Fome, Centro - Centro, Guarapari - ES, 29200-330',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Centro',
    'latitude': -20.6724057,
    'longitude': -40.498251,
    'rating': 3.2,
  },
  {
    'name': 'BANCO DO BRASIL - MUQUICABA - Agência 4629',
    'description': '',
    'address':
        'Av. José Alcântara Bourguignon, 90 - Muquiçaba, Guarapari - ES, 29215-450',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Muquiçaba',
    'latitude': -20.6526732,
    'longitude': -40.4981167,
    'rating': 2.9,
  },
  {
    'name': 'GUARAPARI-CTO .',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 2800 - Aeroporto, Guarapari - ES, 29216-705',
    'category': 'Banco',
    'subtypes': 'Bank, ATM',
    'borough': 'Aeroporto',
    'latitude': -20.6528756,
    'longitude': -40.4963582,
    'rating': 3.7,
  },
  {
    'name': 'Super Fácil Banker',
    'description': '',
    'address': '',
    'category': 'Banco',
    'subtypes': 'Bank, Service establishment',
    'borough': '',
    'latitude': -14.4095262,
    'longitude': -51.31668,
    'rating': null,
  },
  {
    'name': 'Federal Savings Bank',
    'description': '',
    'address':
        'Rodovia do sol, SN LT 05 QUADRA III - Jacunem, Guarapari - ES, 29215-005',
    'category': 'Banco',
    'subtypes': 'Bank, ATM',
    'borough': 'Jacunem',
    'latitude': -20.653289,
    'longitude': -40.4963576,
    'rating': 2.8,
  },
  {
    'name': 'Bradesco Muquiçaba',
    'description': '',
    'address': 'Av. Padre José de Anchieta, 2276 - Jacunem, Guarapari - ES',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Jacunem',
    'latitude': -20.6528811,
    'longitude': -40.4963876,
    'rating': 3.1,
  },
  {
    'name': 'Banestes',
    'description': '',
    'address':
        'R. Dinarte dos Santos, 1081 - Muquiçaba, Guarapari - ES, 29215-075',
    'category': 'Caixa eletrônico',
    'subtypes': 'Bank, ATM',
    'borough': 'Muquiçaba',
    'latitude': -20.6592322,
    'longitude': -40.4977969,
    'rating': 4.4,
  },
  {
    'name': 'Sicoob Guarapari - Aeroporto',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 3595 - Aeroporto, Guarapari - ES, 29216-705',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Aeroporto',
    'latitude': -20.6502581,
    'longitude': -40.4937285,
    'rating': 4.8,
  },
  {
    'name': 'Real Cred Empréstimo Consignado',
    'description': '',
    'address': 'R. Augusto de Mattos, 51 - Centro, Guarapari - ES, 29200-310',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Centro',
    'latitude': -20.6695759,
    'longitude': -40.4982253,
    'rating': null,
  },
  {
    'name': 'Elleve Soluçóes Financeiras',
    'description': '',
    'address': 'R. Henrique Coutinho, 84 - Centro, Guarapari - ES, 29200-190',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Centro',
    'latitude': -20.6699951,
    'longitude': -40.4965355,
    'rating': null,
  },
  {
    'name': 'Banesfácil',
    'description': '',
    'address':
        'Av. Padre José de Anchieta, 1499 - Praia do Morro, Guarapari - ES, 29220-545',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Praia do Morro',
    'latitude': -20.6432348,
    'longitude': -40.4864018,
    'rating': 4.8,
  },
  {
    'name': 'bradesco EXPRESSO',
    'description': '',
    'address': 'Av. Oceânica - Praia do Morro, Guarapari - ES, 29216-080',
    'category': 'Banco',
    'subtypes': 'Bank',
    'borough': 'Praia do Morro',
    'latitude': -20.6540199,
    'longitude': -40.4885292,
    'rating': null,
  },
];
