// Mocks generated by Mockito 5.4.6 from annotations
// in belluga_now/test/presentation/tenant/home/screens/tenant_home_provisional_screen/controllers/tenant_home_provisional_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:belluga_now/domain/favorite/projections/favorite_resume.dart'
    as _i4;
import 'package:belluga_now/domain/invites/invite_model.dart' as _i6;
import 'package:belluga_now/domain/venue_event/projections/venue_event_resume.dart'
    as _i5;
import 'package:belluga_now/presentation/tenant/home/screens/tenant_home_screen/controllers/tenant_home_controller.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stream_value/core/stream_value.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamValue_0<T> extends _i1.SmartFake
    implements _i2.StreamValue<T> {
  _FakeStreamValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TenantHomeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTenantHomeController extends _i1.Mock
    implements _i3.TenantHomeController {
  @override
  _i2.StreamValue<List<_i4.FavoriteResume>?> get favoritesStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#favoritesStreamValue),
        returnValue: _FakeStreamValue_0<List<_i4.FavoriteResume>?>(
          this,
          Invocation.getter(#favoritesStreamValue),
        ),
        returnValueForMissingStub:
            _FakeStreamValue_0<List<_i4.FavoriteResume>?>(
          this,
          Invocation.getter(#favoritesStreamValue),
        ),
      ) as _i2.StreamValue<List<_i4.FavoriteResume>?>);

  @override
  _i2.StreamValue<List<_i5.VenueEventResume>> get myEventsStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#myEventsStreamValue),
        returnValue: _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#myEventsStreamValue),
        ),
        returnValueForMissingStub:
            _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#myEventsStreamValue),
        ),
      ) as _i2.StreamValue<List<_i5.VenueEventResume>>);

  @override
  _i2.StreamValue<List<_i5.VenueEventResume>> get upcomingEventsStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#upcomingEventsStreamValue),
        returnValue: _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#upcomingEventsStreamValue),
        ),
        returnValueForMissingStub:
            _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#upcomingEventsStreamValue),
        ),
      ) as _i2.StreamValue<List<_i5.VenueEventResume>>);

  @override
  _i2.StreamValue<List<_i5.VenueEventResume>> get liveEventsStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#liveEventsStreamValue),
        returnValue: _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#liveEventsStreamValue),
        ),
        returnValueForMissingStub:
            _FakeStreamValue_0<List<_i5.VenueEventResume>>(
          this,
          Invocation.getter(#liveEventsStreamValue),
        ),
      ) as _i2.StreamValue<List<_i5.VenueEventResume>>);

  @override
  _i2.StreamValue<String?> get userAddressStreamValue => (super.noSuchMethod(
        Invocation.getter(#userAddressStreamValue),
        returnValue: _FakeStreamValue_0<String?>(
          this,
          Invocation.getter(#userAddressStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<String?>(
          this,
          Invocation.getter(#userAddressStreamValue),
        ),
      ) as _i2.StreamValue<String?>);

  @override
  _i2.StreamValue<Set<String>> get confirmedIdsStream => (super.noSuchMethod(
        Invocation.getter(#confirmedIdsStream),
        returnValue: _FakeStreamValue_0<Set<String>>(
          this,
          Invocation.getter(#confirmedIdsStream),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<Set<String>>(
          this,
          Invocation.getter(#confirmedIdsStream),
        ),
      ) as _i2.StreamValue<Set<String>>);

  @override
  _i2.StreamValue<List<_i6.InviteModel>> get pendingInvitesStreamValue =>
      (super.noSuchMethod(
        Invocation.getter(#pendingInvitesStreamValue),
        returnValue: _FakeStreamValue_0<List<_i6.InviteModel>>(
          this,
          Invocation.getter(#pendingInvitesStreamValue),
        ),
        returnValueForMissingStub: _FakeStreamValue_0<List<_i6.InviteModel>>(
          this,
          Invocation.getter(#pendingInvitesStreamValue),
        ),
      ) as _i2.StreamValue<List<_i6.InviteModel>>);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadFavorites() => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadMyEvents() => (super.noSuchMethod(
        Invocation.method(
          #loadMyEvents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadUpcomingEvents() => (super.noSuchMethod(
        Invocation.method(
          #loadUpcomingEvents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  String? distanceLabelFor(_i5.VenueEventResume? event) => (super.noSuchMethod(
        Invocation.method(
          #distanceLabelFor,
          [event],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  void onDispose() => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
